/**
 * SDN-O SPTN Controller Driver SBI Interface
 * SDN-O SPTN Controller Driver SBI Interface
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.south;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * CreateElineAndTunnels
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T10:40:00.335+08:00")
public class CreateElineAndTunnels {

  @SerializedName("snc-eline")
  private Eline sncEline = null;

  @SerializedName("route-cal-result")
  private List<RouteCalResult> routeCalResult = new ArrayList<RouteCalResult>();

  @SerializedName("snc-tunnel-create-policy")
  private SncTunnelCreatePolicy sncTunnelCreatePolicy = null;

  public CreateElineAndTunnels sncEline(Eline sncEline) {
    this.sncEline = sncEline;
    return this;
  }

  /**
   * Get sncEline
   *
   * @return sncEline
   */
  @ApiModelProperty(example = "null", required = true, value = "")
  public Eline getSncEline() {
    return sncEline;
  }

  public void setSncEline(Eline sncEline) {
    this.sncEline = sncEline;
  }

  public CreateElineAndTunnels routeCalResult(List<RouteCalResult> routeCalResult) {
    this.routeCalResult = routeCalResult;
    return this;
  }

  /**
   * Get routeCalResult
   *
   * @return routeCalResult
   */
  @ApiModelProperty(example = "null", value = "")
  public List<RouteCalResult> getRouteCalResult() {
    return routeCalResult;
  }

  public void setRouteCalResult(List<RouteCalResult> routeCalResult) {
    this.routeCalResult = routeCalResult;
  }

  public CreateElineAndTunnels sncTunnelCreatePolicy(SncTunnelCreatePolicy sncTunnelCreatePolicy) {
    this.sncTunnelCreatePolicy = sncTunnelCreatePolicy;
    return this;
  }

  /**
   * Get sncTunnelCreatePolicy
   *
   * @return sncTunnelCreatePolicy
   */
  @ApiModelProperty(example = "null", required = true, value = "")
  public SncTunnelCreatePolicy getSncTunnelCreatePolicy() {
    return sncTunnelCreatePolicy;
  }

  public void setSncTunnelCreatePolicy(SncTunnelCreatePolicy sncTunnelCreatePolicy) {
    this.sncTunnelCreatePolicy = sncTunnelCreatePolicy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateElineAndTunnels createElineAndTunnels = (CreateElineAndTunnels) o;
    return Objects.equals(this.sncEline, createElineAndTunnels.sncEline) &&
           Objects.equals(this.routeCalResult, createElineAndTunnels.routeCalResult) &&
           Objects.equals(this.sncTunnelCreatePolicy, createElineAndTunnels.sncTunnelCreatePolicy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sncEline, routeCalResult, sncTunnelCreatePolicy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateElineAndTunnels {\n");

    sb.append("    sncEline: ").append(toIndentedString(sncEline)).append("\n");
    sb.append("    routeCalResult: ").append(toIndentedString(routeCalResult)).append("\n");
    sb.append("    sncTunnelCreatePolicy: ").append(toIndentedString(sncTunnelCreatePolicy))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

