/**
 * SDN-O SPTN Controller Driver SBI Interface
 * SDN-O SPTN Controller Driver SBI Interface
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.south;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * L3ac
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T10:40:00.335+08:00")
public class L3ac {

  @SerializedName("id")
  private String id = null;

  @SerializedName("ne-id")
  private String neId = null;

  @SerializedName("ltp-id")
  private String ltpId = null;

  @SerializedName("ip-addr")
  private String ipAddr = null;

  public L3ac id(String id) {
    this.id = id;
    return this;
  }

  /**
   * L3vpn AC UUID
   *
   * @return id
   */
  @ApiModelProperty(example = "null", value = "L3vpn AC UUID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public L3ac neId(String neId) {
    this.neId = neId;
    return this;
  }

  /**
   * NE UUID
   *
   * @return neId
   */
  @ApiModelProperty(example = "null", value = "NE UUID")
  public String getNeId() {
    return neId;
  }

  public void setNeId(String neId) {
    this.neId = neId;
  }

  public L3ac ltpId(String ltpId) {
    this.ltpId = ltpId;
    return this;
  }

  /**
   * LTP UUID
   *
   * @return ltpId
   */
  @ApiModelProperty(example = "null", value = "LTP UUID")
  public String getLtpId() {
    return ltpId;
  }

  public void setLtpId(String ltpId) {
    this.ltpId = ltpId;
  }

  public L3ac ipAddr(String ipAddr) {
    this.ipAddr = ipAddr;
    return this;
  }

  /**
   * New private IP address of LTP after  added to L3vpn
   *
   * @return ipAddr
   */
  @ApiModelProperty(example = "null", value = "New private IP address of LTP after  added to L3vpn")
  public String getIpAddr() {
    return ipAddr;
  }

  public void setIpAddr(String ipAddr) {
    this.ipAddr = ipAddr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    L3ac l3ac = (L3ac) o;
    return Objects.equals(this.id, l3ac.id) &&
           Objects.equals(this.neId, l3ac.neId) &&
           Objects.equals(this.ltpId, l3ac.ltpId) &&
           Objects.equals(this.ipAddr, l3ac.ipAddr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, neId, ltpId, ipAddr);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class L3ac {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    neId: ").append(toIndentedString(neId)).append("\n");
    sb.append("    ltpId: ").append(toIndentedString(ltpId)).append("\n");
    sb.append("    ipAddr: ").append(toIndentedString(ipAddr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

