/**
 * SDN-O SPTN Controller Driver SBI Interface
 * SDN-O SPTN Controller Driver SBI Interface
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.south;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * L3BindRelation
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T10:40:00.335+08:00")
public class L3BindRelation {

  @SerializedName("source-peer")
  private String sourcePeer = null;

  @SerializedName("dest-peer")
  private String destPeer = null;

  @SerializedName("source-id")
  private String sourceId = null;

  @SerializedName("dest-id")
  private String destId = null;

  @SerializedName("tunnel-policy")
  private SncTunnelCreatePolicy tunnelPolicy = null;

  @SerializedName("bound-obj")
  private String boundObj = null;

  public L3BindRelation sourcePeer(String sourcePeer) {
    this.sourcePeer = sourcePeer;
    return this;
  }

  /**
   * Peer IP address of souce end
   *
   * @return sourcePeer
   */
  @ApiModelProperty(example = "null", value = "Peer IP address of souce end")
  public String getSourcePeer() {
    return sourcePeer;
  }

  public void setSourcePeer(String sourcePeer) {
    this.sourcePeer = sourcePeer;
  }

  public L3BindRelation destPeer(String destPeer) {
    this.destPeer = destPeer;
    return this;
  }

  /**
   * Peer IP address of destination end
   *
   * @return destPeer
   */
  @ApiModelProperty(example = "null", value = "Peer IP address of destination end")
  public String getDestPeer() {
    return destPeer;
  }

  public void setDestPeer(String destPeer) {
    this.destPeer = destPeer;
  }

  public L3BindRelation sourceId(String sourceId) {
    this.sourceId = sourceId;
    return this;
  }

  /**
   * UUID of source NE
   *
   * @return sourceId
   */
  @ApiModelProperty(example = "null", value = "UUID of source NE")
  public String getSourceId() {
    return sourceId;
  }

  public void setSourceId(String sourceId) {
    this.sourceId = sourceId;
  }

  public L3BindRelation destId(String destId) {
    this.destId = destId;
    return this;
  }

  /**
   * UUID of destination NE
   *
   * @return destId
   */
  @ApiModelProperty(example = "null", value = "UUID of destination NE")
  public String getDestId() {
    return destId;
  }

  public void setDestId(String destId) {
    this.destId = destId;
  }

  public L3BindRelation tunnelPolicy(SncTunnelCreatePolicy tunnelPolicy) {
    this.tunnelPolicy = tunnelPolicy;
    return this;
  }

  /**
   * Get tunnelPolicy
   *
   * @return tunnelPolicy
   */
  @ApiModelProperty(example = "null", value = "")
  public SncTunnelCreatePolicy getTunnelPolicy() {
    return tunnelPolicy;
  }

  public void setTunnelPolicy(SncTunnelCreatePolicy tunnelPolicy) {
    this.tunnelPolicy = tunnelPolicy;
  }

  public L3BindRelation boundObj(String boundObj) {
    this.boundObj = boundObj;
    return this;
  }

  /**
   * UUID of binding tunnel
   *
   * @return boundObj
   */
  @ApiModelProperty(example = "null", value = "UUID of binding tunnel")
  public String getBoundObj() {
    return boundObj;
  }

  public void setBoundObj(String boundObj) {
    this.boundObj = boundObj;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    L3BindRelation l3BindRelation = (L3BindRelation) o;
    return Objects.equals(this.sourcePeer, l3BindRelation.sourcePeer) &&
           Objects.equals(this.destPeer, l3BindRelation.destPeer) &&
           Objects.equals(this.sourceId, l3BindRelation.sourceId) &&
           Objects.equals(this.destId, l3BindRelation.destId) &&
           Objects.equals(this.tunnelPolicy, l3BindRelation.tunnelPolicy) &&
           Objects.equals(this.boundObj, l3BindRelation.boundObj);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourcePeer, destPeer, sourceId, destId, tunnelPolicy, boundObj);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class L3BindRelation {\n");

    sb.append("    sourcePeer: ").append(toIndentedString(sourcePeer)).append("\n");
    sb.append("    destPeer: ").append(toIndentedString(destPeer)).append("\n");
    sb.append("    sourceId: ").append(toIndentedString(sourceId)).append("\n");
    sb.append("    destId: ").append(toIndentedString(destId)).append("\n");
    sb.append("    tunnelPolicy: ").append(toIndentedString(tunnelPolicy)).append("\n");
    sb.append("    boundObj: ").append(toIndentedString(boundObj)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

