/**
 * SDN-O SPTN Controller Driver SBI Interface
 * SDN-O SPTN Controller Driver SBI Interface
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.south;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * QOS
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T10:40:00.335+08:00")
public class QOS {

  @SerializedName("belonged-id")
  private String belongedId = null;

  @SerializedName("tunnel-mode")
  private Integer tunnelMode = null;

  @SerializedName("cac-mode")
  private Integer cacMode = null;

  @SerializedName("convg-mode")
  private Integer convgMode = null;

  @SerializedName("traffic-adj-mode")
  private Integer trafficAdjMode = null;

  @SerializedName("a2z-policing")
  private Integer a2zPolicing = null;

  @SerializedName("z2a-policing")
  private Integer z2aPolicing = null;

  @SerializedName("a2z-cir")
  private Integer a2zCir = null;

  @SerializedName("z2a-cir")
  private Integer z2aCir = null;

  @SerializedName("a2z-pir")
  private Integer a2zPir = null;

  @SerializedName("z2a-pir")
  private Integer z2aPir = null;

  @SerializedName("a2z-cbs")
  private Integer a2zCbs = null;

  @SerializedName("z2a-cbs")
  private Integer z2aCbs = null;

  @SerializedName("a2z-pbs")
  private Integer a2zPbs = null;

  @SerializedName("z2a-pbs")
  private Integer z2aPbs = null;

  @SerializedName("a2z-color-mode")
  private Integer a2zColorMode = null;

  @SerializedName("z2a-color-mode")
  private Integer z2aColorMode = null;

  @SerializedName("traffic-class")
  private Integer trafficClass = null;

  public QOS belongedId(String belongedId) {
    this.belongedId = belongedId;
    return this;
  }

  /**
   * The UUID of OAM related object
   *
   * @return belongedId
   */
  @ApiModelProperty(example = "null", required = true, value = "The UUID of OAM related object")
  public String getBelongedId() {
    return belongedId;
  }

  public void setBelongedId(String belongedId) {
    this.belongedId = belongedId;
  }

  public QOS tunnelMode(Integer tunnelMode) {
    this.tunnelMode = tunnelMode;
    return this;
  }

  /**
   * The tunnel mode, including 1(pipeline), 2(short-pipeline), 3(unified-pattern)
   *
   * @return tunnelMode
   */
  @ApiModelProperty(example = "null",
                    value = "The tunnel mode, including 1(pipeline), 2(short-pipeline), 3(unified-pattern)")
  public Integer getTunnelMode() {
    return tunnelMode;
  }

  public void setTunnelMode(Integer tunnelMode) {
    this.tunnelMode = tunnelMode;
  }

  public QOS cacMode(Integer cacMode) {
    this.cacMode = cacMode;
    return this;
  }

  /**
   * Whether CAC is enabled, including 0(disable), 1(enable)
   *
   * @return cacMode
   */
  @ApiModelProperty(example = "null",
                    value = "Whether CAC is enabled, including 0(disable), 1(enable)")
  public Integer getCacMode() {
    return cacMode;
  }

  public void setCacMode(Integer cacMode) {
    this.cacMode = cacMode;
  }

  public QOS convgMode(Integer convgMode) {
    this.convgMode = convgMode;
    return this;
  }

  /**
   * Whether the tunnel inherits the convege rate of TMS, including 0(not convergence), 1(use TMS
   * convergence rate)
   *
   * @return convgMode
   */
  @ApiModelProperty(example = "null",
                    value = "Whether the tunnel inherits the convege rate of TMS, including 0(not convergence), 1(use TMS convergence rate)")
  public Integer getConvgMode() {
    return convgMode;
  }

  public void setConvgMode(Integer convgMode) {
    this.convgMode = convgMode;
  }

  public QOS trafficAdjMode(Integer trafficAdjMode) {
    this.trafficAdjMode = trafficAdjMode;
    return this;
  }

  /**
   * Whether the traffic parameters(like Cir, Pir) of the tunnel can be automatically changed with
   * the change of client service, including 0(not support auto-adjust), 1(support auto-adjust)
   *
   * @return trafficAdjMode
   */
  @ApiModelProperty(example = "null",
                    value = "Whether the traffic parameters(like Cir, Pir) of the tunnel can be automatically changed with the change of client service, including 0(not support auto-adjust), 1(support auto-adjust)")
  public Integer getTrafficAdjMode() {
    return trafficAdjMode;
  }

  public void setTrafficAdjMode(Integer trafficAdjMode) {
    this.trafficAdjMode = trafficAdjMode;
  }

  public QOS a2zPolicing(Integer a2zPolicing) {
    this.a2zPolicing = a2zPolicing;
    return this;
  }

  /**
   * Whether a2z policing is enabled, including 0(disabled), 1(enabled)
   *
   * @return a2zPolicing
   */
  @ApiModelProperty(example = "null",
                    value = "Whether a2z policing is enabled, including 0(disabled), 1(enabled)")
  public Integer getA2zPolicing() {
    return a2zPolicing;
  }

  public void setA2zPolicing(Integer a2zPolicing) {
    this.a2zPolicing = a2zPolicing;
  }

  public QOS z2aPolicing(Integer z2aPolicing) {
    this.z2aPolicing = z2aPolicing;
    return this;
  }

  /**
   * Whether z2a policing is enabled, including 0(disabled), 1(enabled)
   *
   * @return z2aPolicing
   */
  @ApiModelProperty(example = "null",
                    value = "Whether z2a policing is enabled, including 0(disabled), 1(enabled)")
  public Integer getZ2aPolicing() {
    return z2aPolicing;
  }

  public void setZ2aPolicing(Integer z2aPolicing) {
    this.z2aPolicing = z2aPolicing;
  }

  public QOS a2zCir(Integer a2zCir) {
    this.a2zCir = a2zCir;
    return this;
  }

  /**
   * The a2z committed speed in kbps
   *
   * @return a2zCir
   */
  @ApiModelProperty(example = "null", value = "The a2z committed speed in kbps")
  public Integer getA2zCir() {
    return a2zCir;
  }

  public void setA2zCir(Integer a2zCir) {
    this.a2zCir = a2zCir;
  }

  public QOS z2aCir(Integer z2aCir) {
    this.z2aCir = z2aCir;
    return this;
  }

  /**
   * The z2a Committed speed in kbps
   *
   * @return z2aCir
   */
  @ApiModelProperty(example = "null", value = "The z2a Committed speed in kbps")
  public Integer getZ2aCir() {
    return z2aCir;
  }

  public void setZ2aCir(Integer z2aCir) {
    this.z2aCir = z2aCir;
  }

  public QOS a2zPir(Integer a2zPir) {
    this.a2zPir = a2zPir;
    return this;
  }

  /**
   * The a2z peak speed in kbps
   *
   * @return a2zPir
   */
  @ApiModelProperty(example = "null", value = "The a2z peak speed in kbps")
  public Integer getA2zPir() {
    return a2zPir;
  }

  public void setA2zPir(Integer a2zPir) {
    this.a2zPir = a2zPir;
  }

  public QOS z2aPir(Integer z2aPir) {
    this.z2aPir = z2aPir;
    return this;
  }

  /**
   * The z2a peak speed in kbps
   *
   * @return z2aPir
   */
  @ApiModelProperty(example = "null", value = "The z2a peak speed in kbps")
  public Integer getZ2aPir() {
    return z2aPir;
  }

  public void setZ2aPir(Integer z2aPir) {
    this.z2aPir = z2aPir;
  }

  public QOS a2zCbs(Integer a2zCbs) {
    this.a2zCbs = a2zCbs;
    return this;
  }

  /**
   * The a2z committed burst Size in  bytes
   *
   * @return a2zCbs
   */
  @ApiModelProperty(example = "null", value = "The a2z committed burst Size in  bytes")
  public Integer getA2zCbs() {
    return a2zCbs;
  }

  public void setA2zCbs(Integer a2zCbs) {
    this.a2zCbs = a2zCbs;
  }

  public QOS z2aCbs(Integer z2aCbs) {
    this.z2aCbs = z2aCbs;
    return this;
  }

  /**
   * The z2a committed burst Size in  bytes
   *
   * @return z2aCbs
   */
  @ApiModelProperty(example = "null", value = "The z2a committed burst Size in  bytes")
  public Integer getZ2aCbs() {
    return z2aCbs;
  }

  public void setZ2aCbs(Integer z2aCbs) {
    this.z2aCbs = z2aCbs;
  }

  public QOS a2zPbs(Integer a2zPbs) {
    this.a2zPbs = a2zPbs;
    return this;
  }

  /**
   * The a2z peak burst Size in bytes
   *
   * @return a2zPbs
   */
  @ApiModelProperty(example = "null", value = "The a2z peak burst Size in bytes")
  public Integer getA2zPbs() {
    return a2zPbs;
  }

  public void setA2zPbs(Integer a2zPbs) {
    this.a2zPbs = a2zPbs;
  }

  public QOS z2aPbs(Integer z2aPbs) {
    this.z2aPbs = z2aPbs;
    return this;
  }

  /**
   * The z2a peak burst Size in bytes
   *
   * @return z2aPbs
   */
  @ApiModelProperty(example = "null", value = "The z2a peak burst Size in bytes")
  public Integer getZ2aPbs() {
    return z2aPbs;
  }

  public void setZ2aPbs(Integer z2aPbs) {
    this.z2aPbs = z2aPbs;
  }

  public QOS a2zColorMode(Integer a2zColorMode) {
    this.a2zColorMode = a2zColorMode;
    return this;
  }

  /**
   * The a2z color mode, including 0(blind), 1(aware)
   *
   * @return a2zColorMode
   */
  @ApiModelProperty(example = "null", value = "The a2z color mode, including 0(blind), 1(aware)")
  public Integer getA2zColorMode() {
    return a2zColorMode;
  }

  public void setA2zColorMode(Integer a2zColorMode) {
    this.a2zColorMode = a2zColorMode;
  }

  public QOS z2aColorMode(Integer z2aColorMode) {
    this.z2aColorMode = z2aColorMode;
    return this;
  }

  /**
   * The z2a color mode, including 0(blind), 1(aware)
   *
   * @return z2aColorMode
   */
  @ApiModelProperty(example = "null", value = "The z2a color mode, including 0(blind), 1(aware)")
  public Integer getZ2aColorMode() {
    return z2aColorMode;
  }

  public void setZ2aColorMode(Integer z2aColorMode) {
    this.z2aColorMode = z2aColorMode;
  }

  public QOS trafficClass(Integer trafficClass) {
    this.trafficClass = trafficClass;
    return this;
  }

  /**
   * The traffic class, including 0(BE), 1(AF1), 2(AF2), 3(AF3), 4(AF4), 5(AF5), 6(CS6), 7(CS7)
   *
   * @return trafficClass
   */
  @ApiModelProperty(example = "null",
                    value = "The traffic class, including 0(BE), 1(AF1), 2(AF2), 3(AF3), 4(AF4), 5(AF5), 6(CS6), 7(CS7)")
  public Integer getTrafficClass() {
    return trafficClass;
  }

  public void setTrafficClass(Integer trafficClass) {
    this.trafficClass = trafficClass;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QOS QOS = (QOS) o;
    return Objects.equals(this.belongedId, QOS.belongedId) &&
           Objects.equals(this.tunnelMode, QOS.tunnelMode) &&
           Objects.equals(this.cacMode, QOS.cacMode) &&
           Objects.equals(this.convgMode, QOS.convgMode) &&
           Objects.equals(this.trafficAdjMode, QOS.trafficAdjMode) &&
           Objects.equals(this.a2zPolicing, QOS.a2zPolicing) &&
           Objects.equals(this.z2aPolicing, QOS.z2aPolicing) &&
           Objects.equals(this.a2zCir, QOS.a2zCir) &&
           Objects.equals(this.z2aCir, QOS.z2aCir) &&
           Objects.equals(this.a2zPir, QOS.a2zPir) &&
           Objects.equals(this.z2aPir, QOS.z2aPir) &&
           Objects.equals(this.a2zCbs, QOS.a2zCbs) &&
           Objects.equals(this.z2aCbs, QOS.z2aCbs) &&
           Objects.equals(this.a2zPbs, QOS.a2zPbs) &&
           Objects.equals(this.z2aPbs, QOS.z2aPbs) &&
           Objects.equals(this.a2zColorMode, QOS.a2zColorMode) &&
           Objects.equals(this.z2aColorMode, QOS.z2aColorMode) &&
           Objects.equals(this.trafficClass, QOS.trafficClass);
  }

  @Override
  public int hashCode() {
    return Objects
        .hash(belongedId, tunnelMode, cacMode, convgMode, trafficAdjMode, a2zPolicing, z2aPolicing,
              a2zCir, z2aCir, a2zPir, z2aPir, a2zCbs, z2aCbs, a2zPbs, z2aPbs, a2zColorMode,
              z2aColorMode, trafficClass);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QOS {\n");

    sb.append("    belongedId: ").append(toIndentedString(belongedId)).append("\n");
    sb.append("    tunnelMode: ").append(toIndentedString(tunnelMode)).append("\n");
    sb.append("    cacMode: ").append(toIndentedString(cacMode)).append("\n");
    sb.append("    convgMode: ").append(toIndentedString(convgMode)).append("\n");
    sb.append("    trafficAdjMode: ").append(toIndentedString(trafficAdjMode)).append("\n");
    sb.append("    a2zPolicing: ").append(toIndentedString(a2zPolicing)).append("\n");
    sb.append("    z2aPolicing: ").append(toIndentedString(z2aPolicing)).append("\n");
    sb.append("    a2zCir: ").append(toIndentedString(a2zCir)).append("\n");
    sb.append("    z2aCir: ").append(toIndentedString(z2aCir)).append("\n");
    sb.append("    a2zPir: ").append(toIndentedString(a2zPir)).append("\n");
    sb.append("    z2aPir: ").append(toIndentedString(z2aPir)).append("\n");
    sb.append("    a2zCbs: ").append(toIndentedString(a2zCbs)).append("\n");
    sb.append("    z2aCbs: ").append(toIndentedString(z2aCbs)).append("\n");
    sb.append("    a2zPbs: ").append(toIndentedString(a2zPbs)).append("\n");
    sb.append("    z2aPbs: ").append(toIndentedString(z2aPbs)).append("\n");
    sb.append("    a2zColorMode: ").append(toIndentedString(a2zColorMode)).append("\n");
    sb.append("    z2aColorMode: ").append(toIndentedString(z2aColorMode)).append("\n");
    sb.append("    trafficClass: ").append(toIndentedString(trafficClass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

