/**
 * SDN-O SPTN Controller Driver SBI Interface
 * SDN-O SPTN Controller Driver SBI Interface
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.south;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Tunnel route calculate result
 */
@ApiModel(description = "Tunnel route calculate result")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T10:40:00.335+08:00")
public class RouteCalResult {

  @SerializedName("sequence-no")
  private String sequenceNo = "1";

  @SerializedName("group-no")
  private String groupNo = null;

  @SerializedName("role")
  private Integer role = null;

  @SerializedName("ingress-ne-id")
  private String ingressNeId = null;

  @SerializedName("egress-ne-id")
  private String egressNeId = null;

  @SerializedName("latency")
  private Integer latency = null;

  @SerializedName("max-availble-bandwidth")
  private Integer maxAvailbleBandwidth = null;

  @SerializedName("xcs")
  private List<XC> xcs = new ArrayList<XC>();

  public RouteCalResult sequenceNo(String sequenceNo) {
    this.sequenceNo = sequenceNo;
    return this;
  }

  /**
   * Sequence number
   *
   * @return sequenceNo
   */
  @ApiModelProperty(example = "null", required = true, value = "Sequence number")
  public String getSequenceNo() {
    return sequenceNo;
  }

  public void setSequenceNo(String sequenceNo) {
    this.sequenceNo = sequenceNo;
  }

  public RouteCalResult groupNo(String groupNo) {
    this.groupNo = groupNo;
    return this;
  }

  /**
   * Group number of tunnel
   *
   * @return groupNo
   */
  @ApiModelProperty(example = "null", required = true, value = "Group number of tunnel")
  public String getGroupNo() {
    return groupNo;
  }

  public void setGroupNo(String groupNo) {
    this.groupNo = groupNo;
  }

  public RouteCalResult role(Integer role) {
    this.role = role;
    return this;
  }

  /**
   * Role of tunnel, including 1(master),2(slave), 3(reroute)
   *
   * @return role
   */
  @ApiModelProperty(example = "null",
                    value = "Role of tunnel, including 1(master),2(slave), 3(reroute)")
  public Integer getRole() {
    return role;
  }

  public void setRole(Integer role) {
    this.role = role;
  }

  public RouteCalResult ingressNeId(String ingressNeId) {
    this.ingressNeId = ingressNeId;
    return this;
  }

  /**
   * Source NE UUID
   *
   * @return ingressNeId
   */
  @ApiModelProperty(example = "null", value = "Source NE UUID")
  public String getIngressNeId() {
    return ingressNeId;
  }

  public void setIngressNeId(String ingressNeId) {
    this.ingressNeId = ingressNeId;
  }

  public RouteCalResult egressNeId(String egressNeId) {
    this.egressNeId = egressNeId;
    return this;
  }

  /**
   * Destination NE UUID
   *
   * @return egressNeId
   */
  @ApiModelProperty(example = "null", value = "Destination NE UUID")
  public String getEgressNeId() {
    return egressNeId;
  }

  public void setEgressNeId(String egressNeId) {
    this.egressNeId = egressNeId;
  }

  public RouteCalResult latency(Integer latency) {
    this.latency = latency;
    return this;
  }

  /**
   * Latency of tunnel in us, range from 0 to 60000000
   *
   * @return latency
   */
  @ApiModelProperty(example = "null", value = "Latency of tunnel in us, range from 0 to 60000000")
  public Integer getLatency() {
    return latency;
  }

  public void setLatency(Integer latency) {
    this.latency = latency;
  }

  public RouteCalResult maxAvailbleBandwidth(Integer maxAvailbleBandwidth) {
    this.maxAvailbleBandwidth = maxAvailbleBandwidth;
    return this;
  }

  /**
   * The minimum max available bandwidth of all links bearing the tunnel in kps, range from 0 to
   * 4000000000
   *
   * @return maxAvailbleBandwidth
   */
  @ApiModelProperty(example = "null",
                    value = "The minimum max available bandwidth of all links bearing the tunnel in kps, range from 0 to 4000000000")
  public Integer getMaxAvailbleBandwidth() {
    return maxAvailbleBandwidth;
  }

  public void setMaxAvailbleBandwidth(Integer maxAvailbleBandwidth) {
    this.maxAvailbleBandwidth = maxAvailbleBandwidth;
  }

  public RouteCalResult xcs(List<XC> xcs) {
    this.xcs = xcs;
    return this;
  }

  /**
   * Get xcs
   *
   * @return xcs
   */
  @ApiModelProperty(example = "null", value = "")
  public List<XC> getXcs() {
    return xcs;
  }

  public void setXcs(List<XC> xcs) {
    this.xcs = xcs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RouteCalResult routeCalResult = (RouteCalResult) o;
    return Objects.equals(this.sequenceNo, routeCalResult.sequenceNo) &&
           Objects.equals(this.groupNo, routeCalResult.groupNo) &&
           Objects.equals(this.role, routeCalResult.role) &&
           Objects.equals(this.ingressNeId, routeCalResult.ingressNeId) &&
           Objects.equals(this.egressNeId, routeCalResult.egressNeId) &&
           Objects.equals(this.latency, routeCalResult.latency) &&
           Objects.equals(this.maxAvailbleBandwidth, routeCalResult.maxAvailbleBandwidth) &&
           Objects.equals(this.xcs, routeCalResult.xcs);
  }

  @Override
  public int hashCode() {
    return Objects
        .hash(sequenceNo, groupNo, role, ingressNeId, egressNeId, latency, maxAvailbleBandwidth,
              xcs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RouteCalResult {\n");

    sb.append("    sequenceNo: ").append(toIndentedString(sequenceNo)).append("\n");
    sb.append("    groupNo: ").append(toIndentedString(groupNo)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    ingressNeId: ").append(toIndentedString(ingressNeId)).append("\n");
    sb.append("    egressNeId: ").append(toIndentedString(egressNeId)).append("\n");
    sb.append("    latency: ").append(toIndentedString(latency)).append("\n");
    sb.append("    maxAvailbleBandwidth: ").append(toIndentedString(maxAvailbleBandwidth))
        .append("\n");
    sb.append("    xcs: ").append(toIndentedString(xcs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

