/**
 * SDN-O SPTN Controller Driver SBI Interface
 * SDN-O SPTN Controller Driver SBI Interface
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.south;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * The service end points(EP)
 */
@ApiModel(description = "The service end points(EP)")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T10:40:00.335+08:00")
public class ServiceEndPoint {

  @SerializedName("id")
  private String id = null;

  @SerializedName("ne-id")
  private String neId = null;

  @SerializedName("ltp-id")
  private String ltpId = null;

  @SerializedName("access-type")
  private Integer accessType = null;

  @SerializedName("dot1q-vlan-bitmap")
  private Integer dot1qVlanBitmap = null;

  @SerializedName("qinq-svlan-bitmap")
  private Integer qinqSvlanBitmap = null;

  @SerializedName("qinq-cvlan-bitmap")
  private Integer qinqCvlanBitmap = null;

  @SerializedName("access-action")
  private Integer accessAction = null;

  @SerializedName("access-vlan-id")
  private Integer accessVlanId = null;

  @SerializedName("role")
  private Integer role = null;

  @SerializedName("oam")
  private OAM oam = null;

  @SerializedName("qos")
  private QOS qos = null;

  public ServiceEndPoint id(String id) {
    this.id = id;
    return this;
  }

  /**
   * EP UUID
   *
   * @return id
   */
  @ApiModelProperty(example = "null", required = true, value = "EP UUID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ServiceEndPoint neId(String neId) {
    this.neId = neId;
    return this;
  }

  /**
   * NE UUID
   *
   * @return neId
   */
  @ApiModelProperty(example = "null", required = true, value = "NE UUID")
  public String getNeId() {
    return neId;
  }

  public void setNeId(String neId) {
    this.neId = neId;
  }

  public ServiceEndPoint ltpId(String ltpId) {
    this.ltpId = ltpId;
    return this;
  }

  /**
   * Logical terminal point UUID
   *
   * @return ltpId
   */
  @ApiModelProperty(example = "null", required = true, value = "Logical terminal point UUID")
  public String getLtpId() {
    return ltpId;
  }

  public void setLtpId(String ltpId) {
    this.ltpId = ltpId;
  }

  public ServiceEndPoint accessType(Integer accessType) {
    this.accessType = accessType;
    return this;
  }

  /**
   * The access type, including 1(Port), 2(Dot1Q), 3(QinQ)
   *
   * @return accessType
   */
  @ApiModelProperty(example = "null",
                    value = "The access type, including 1(Port), 2(Dot1Q), 3(QinQ)")
  public Integer getAccessType() {
    return accessType;
  }

  public void setAccessType(Integer accessType) {
    this.accessType = accessType;
  }

  public ServiceEndPoint dot1qVlanBitmap(Integer dot1qVlanBitmap) {
    this.dot1qVlanBitmap = dot1qVlanBitmap;
    return this;
  }

  /**
   * The vlan bitmap of Dot1Q, range from 1 to 4094 minimum: 1.0 maximum: 4094.0
   *
   * @return dot1qVlanBitmap
   */
  @ApiModelProperty(example = "null", value = "The vlan bitmap of Dot1Q, range from 1 to 4094")
  public Integer getDot1qVlanBitmap() {
    return dot1qVlanBitmap;
  }

  public void setDot1qVlanBitmap(Integer dot1qVlanBitmap) {
    this.dot1qVlanBitmap = dot1qVlanBitmap;
  }

  public ServiceEndPoint qinqSvlanBitmap(Integer qinqSvlanBitmap) {
    this.qinqSvlanBitmap = qinqSvlanBitmap;
    return this;
  }

  /**
   * the svlan bitmap of QinQ, range from 1 to 4094 minimum: 1.0 maximum: 4094.0
   *
   * @return qinqSvlanBitmap
   */
  @ApiModelProperty(example = "null", value = "the svlan bitmap of QinQ, range from 1 to 4094")
  public Integer getQinqSvlanBitmap() {
    return qinqSvlanBitmap;
  }

  public void setQinqSvlanBitmap(Integer qinqSvlanBitmap) {
    this.qinqSvlanBitmap = qinqSvlanBitmap;
  }

  public ServiceEndPoint qinqCvlanBitmap(Integer qinqCvlanBitmap) {
    this.qinqCvlanBitmap = qinqCvlanBitmap;
    return this;
  }

  /**
   * the cvlan bitmap of QinQ, range from 1 to 4094 minimum: 1.0 maximum: 4094.0
   *
   * @return qinqCvlanBitmap
   */
  @ApiModelProperty(example = "null", value = "the cvlan bitmap of QinQ, range from 1 to 4094")
  public Integer getQinqCvlanBitmap() {
    return qinqCvlanBitmap;
  }

  public void setQinqCvlanBitmap(Integer qinqCvlanBitmap) {
    this.qinqCvlanBitmap = qinqCvlanBitmap;
  }

  public ServiceEndPoint accessAction(Integer accessAction) {
    this.accessAction = accessAction;
    return this;
  }

  /**
   * The access action type, including 1(Keep), 2(Push), 3(Pop), 4(Swap)
   *
   * @return accessAction
   */
  @ApiModelProperty(example = "null",
                    value = "The access action type, including 1(Keep), 2(Push), 3(Pop), 4(Swap)")
  public Integer getAccessAction() {
    return accessAction;
  }

  public void setAccessAction(Integer accessAction) {
    this.accessAction = accessAction;
  }

  public ServiceEndPoint accessVlanId(Integer accessVlanId) {
    this.accessVlanId = accessVlanId;
    return this;
  }

  /**
   * The access vlan id, range from 1 to 4094 minimum: 1.0 maximum: 4094.0
   *
   * @return accessVlanId
   */
  @ApiModelProperty(example = "null", value = "The access vlan id, range from 1 to 4094")
  public Integer getAccessVlanId() {
    return accessVlanId;
  }

  public void setAccessVlanId(Integer accessVlanId) {
    this.accessVlanId = accessVlanId;
  }

  public ServiceEndPoint role(Integer role) {
    this.role = role;
    return this;
  }

  /**
   * The role of EP, including 0(master), 1(slave)
   *
   * @return role
   */
  @ApiModelProperty(example = "null", value = "The role of EP, including 0(master), 1(slave)")
  public Integer getRole() {
    return role;
  }

  public void setRole(Integer role) {
    this.role = role;
  }

  public ServiceEndPoint oam(OAM oam) {
    this.oam = oam;
    return this;
  }

  /**
   * Get oam
   *
   * @return oam
   */
  @ApiModelProperty(example = "null", value = "")
  public OAM getOam() {
    return oam;
  }

  public void setOam(OAM oam) {
    this.oam = oam;
  }

  public ServiceEndPoint qos(QOS qos) {
    this.qos = qos;
    return this;
  }

  /**
   * Get qos
   *
   * @return qos
   */
  @ApiModelProperty(example = "null", value = "")
  public QOS getQos() {
    return qos;
  }

  public void setQos(QOS qos) {
    this.qos = qos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceEndPoint serviceEndPoint = (ServiceEndPoint) o;
    return Objects.equals(this.id, serviceEndPoint.id) &&
           Objects.equals(this.neId, serviceEndPoint.neId) &&
           Objects.equals(this.ltpId, serviceEndPoint.ltpId) &&
           Objects.equals(this.accessType, serviceEndPoint.accessType) &&
           Objects.equals(this.dot1qVlanBitmap, serviceEndPoint.dot1qVlanBitmap) &&
           Objects.equals(this.qinqSvlanBitmap, serviceEndPoint.qinqSvlanBitmap) &&
           Objects.equals(this.qinqCvlanBitmap, serviceEndPoint.qinqCvlanBitmap) &&
           Objects.equals(this.accessAction, serviceEndPoint.accessAction) &&
           Objects.equals(this.accessVlanId, serviceEndPoint.accessVlanId) &&
           Objects.equals(this.role, serviceEndPoint.role) &&
           Objects.equals(this.oam, serviceEndPoint.oam) &&
           Objects.equals(this.qos, serviceEndPoint.qos);
  }

  @Override
  public int hashCode() {
    return Objects
        .hash(id, neId, ltpId, accessType, dot1qVlanBitmap, qinqSvlanBitmap, qinqCvlanBitmap,
              accessAction, accessVlanId, role, oam, qos);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceEndPoint {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    neId: ").append(toIndentedString(neId)).append("\n");
    sb.append("    ltpId: ").append(toIndentedString(ltpId)).append("\n");
    sb.append("    accessType: ").append(toIndentedString(accessType)).append("\n");
    sb.append("    dot1qVlanBitmap: ").append(toIndentedString(dot1qVlanBitmap)).append("\n");
    sb.append("    qinqSvlanBitmap: ").append(toIndentedString(qinqSvlanBitmap)).append("\n");
    sb.append("    qinqCvlanBitmap: ").append(toIndentedString(qinqCvlanBitmap)).append("\n");
    sb.append("    accessAction: ").append(toIndentedString(accessAction)).append("\n");
    sb.append("    accessVlanId: ").append(toIndentedString(accessVlanId)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    oam: ").append(toIndentedString(oam)).append("\n");
    sb.append("    qos: ").append(toIndentedString(qos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

