/**
 * SDN-O SPTN Controller Driver SBI Interface
 * SDN-O SPTN Controller Driver SBI Interface
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.south;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * SncPw
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T10:40:00.335+08:00")
public class SncPw {

  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("user-label")
  private String userLabel = null;

  @SerializedName("role")
  private Integer role = null;

  @SerializedName("encaplate-type")
  private Integer encaplateType = null;

  @SerializedName("ingress-ne-id")
  private String ingressNeId = null;

  @SerializedName("egress-ne-id")
  private String egressNeId = null;

  @SerializedName("source-ip")
  private String sourceIp = null;

  @SerializedName("destination-ip")
  private String destinationIp = null;

  @SerializedName("tunnel-ids")
  private List<String> tunnelIds = new ArrayList<String>();

  @SerializedName("admin-status")
  private AdminStatus adminStatus = null;

  @SerializedName("operate-status")
  private OperateStatus operateStatus = null;

  @SerializedName("ctrl-word-support")
  private Integer ctrlWordSupport = null;

  @SerializedName("sn-support")
  private Integer snSupport = null;

  @SerializedName("vccv-type")
  private Integer vccvType = null;

  @SerializedName("conn-ack-type")
  private Integer connAckType = null;

  @SerializedName("oam")
  private OAM oam = null;

  @SerializedName("qos")
  private QOS qos = null;

  public SncPw id(String id) {
    this.id = id;
    return this;
  }

  /**
   * The PW UUID
   *
   * @return id
   */
  @ApiModelProperty(example = "null", required = true, value = "The PW UUID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SncPw name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Only used within domain
   *
   * @return name
   */
  @ApiModelProperty(example = "null", value = "Only used within domain")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SncPw userLabel(String userLabel) {
    this.userLabel = userLabel;
    return this;
  }

  /**
   * User label of PW
   *
   * @return userLabel
   */
  @ApiModelProperty(example = "null", value = "User label of PW")
  public String getUserLabel() {
    return userLabel;
  }

  public void setUserLabel(String userLabel) {
    this.userLabel = userLabel;
  }

  public SncPw role(Integer role) {
    this.role = role;
    return this;
  }

  /**
   * The role of PW, including 0(master), 1(slave), 2(DNI-PW)
   *
   * @return role
   */
  @ApiModelProperty(example = "null",
                    value = "The role of PW, including 0(master), 1(slave), 2(DNI-PW)")
  public Integer getRole() {
    return role;
  }

  public void setRole(Integer role) {
    this.role = role;
  }

  public SncPw encaplateType(Integer encaplateType) {
    this.encaplateType = encaplateType;
    return this;
  }

  /**
   * The encaplate type, including 0(NONE), 4(ethernet-vlan), 5(ethernet)
   *
   * @return encaplateType
   */
  @ApiModelProperty(example = "null",
                    value = "The encaplate type, including 0(NONE), 4(ethernet-vlan), 5(ethernet)")
  public Integer getEncaplateType() {
    return encaplateType;
  }

  public void setEncaplateType(Integer encaplateType) {
    this.encaplateType = encaplateType;
  }

  public SncPw ingressNeId(String ingressNeId) {
    this.ingressNeId = ingressNeId;
    return this;
  }

  /**
   * UUID of source NE
   *
   * @return ingressNeId
   */
  @ApiModelProperty(example = "null", value = "UUID of source NE")
  public String getIngressNeId() {
    return ingressNeId;
  }

  public void setIngressNeId(String ingressNeId) {
    this.ingressNeId = ingressNeId;
  }

  public SncPw egressNeId(String egressNeId) {
    this.egressNeId = egressNeId;
    return this;
  }

  /**
   * UUID of destination NE
   *
   * @return egressNeId
   */
  @ApiModelProperty(example = "null", value = "UUID of destination NE")
  public String getEgressNeId() {
    return egressNeId;
  }

  public void setEgressNeId(String egressNeId) {
    this.egressNeId = egressNeId;
  }

  public SncPw sourceIp(String sourceIp) {
    this.sourceIp = sourceIp;
    return this;
  }

  /**
   * source NE IP address
   *
   * @return sourceIp
   */
  @ApiModelProperty(example = "null", value = "source NE IP address")
  public String getSourceIp() {
    return sourceIp;
  }

  public void setSourceIp(String sourceIp) {
    this.sourceIp = sourceIp;
  }

  public SncPw destinationIp(String destinationIp) {
    this.destinationIp = destinationIp;
    return this;
  }

  /**
   * destination NE IP address
   *
   * @return destinationIp
   */
  @ApiModelProperty(example = "null", value = "destination NE IP address")
  public String getDestinationIp() {
    return destinationIp;
  }

  public void setDestinationIp(String destinationIp) {
    this.destinationIp = destinationIp;
  }

  public SncPw tunnelIds(List<String> tunnelIds) {
    this.tunnelIds = tunnelIds;
    return this;
  }

  /**
   * List of binding Tunnel ID, Only used within domain
   *
   * @return tunnelIds
   */
  @ApiModelProperty(example = "null", value = "List of binding Tunnel ID, Only used within domain")
  public List<String> getTunnelIds() {
    return tunnelIds;
  }

  public void setTunnelIds(List<String> tunnelIds) {
    this.tunnelIds = tunnelIds;
  }

  public SncPw adminStatus(AdminStatus adminStatus) {
    this.adminStatus = adminStatus;
    return this;
  }

  /**
   * Get adminStatus
   *
   * @return adminStatus
   */
  @ApiModelProperty(example = "null", value = "")
  public AdminStatus getAdminStatus() {
    return adminStatus;
  }

  public void setAdminStatus(AdminStatus adminStatus) {
    this.adminStatus = adminStatus;
  }

  public SncPw operateStatus(OperateStatus operateStatus) {
    this.operateStatus = operateStatus;
    return this;
  }

  /**
   * Get operateStatus
   *
   * @return operateStatus
   */
  @ApiModelProperty(example = "null", value = "")
  public OperateStatus getOperateStatus() {
    return operateStatus;
  }

  public void setOperateStatus(OperateStatus operateStatus) {
    this.operateStatus = operateStatus;
  }

  public SncPw ctrlWordSupport(Integer ctrlWordSupport) {
    this.ctrlWordSupport = ctrlWordSupport;
    return this;
  }

  /**
   * The control word type, including 0(Not support), 1(support)
   *
   * @return ctrlWordSupport
   */
  @ApiModelProperty(example = "null",
                    value = "The control word type, including 0(Not support), 1(support)")
  public Integer getCtrlWordSupport() {
    return ctrlWordSupport;
  }

  public void setCtrlWordSupport(Integer ctrlWordSupport) {
    this.ctrlWordSupport = ctrlWordSupport;
  }

  public SncPw snSupport(Integer snSupport) {
    this.snSupport = snSupport;
    return this;
  }

  /**
   * 0(Not support), 1(support)
   *
   * @return snSupport
   */
  @ApiModelProperty(example = "null", value = "0(Not support), 1(support)")
  public Integer getSnSupport() {
    return snSupport;
  }

  public void setSnSupport(Integer snSupport) {
    this.snSupport = snSupport;
  }

  public SncPw vccvType(Integer vccvType) {
    this.vccvType = vccvType;
    return this;
  }

  /**
   * 0(not support VCCV), 1(inbound), 2(outbound), 3(based on TTL), 4(inbound + outbound), 5(inbound
   * +based on TTL), 6(outbound + based on TTL), 7(inbound + outbound + based onTTL)
   *
   * @return vccvType
   */
  @ApiModelProperty(example = "null",
                    value = "0(not support VCCV), 1(inbound), 2(outbound), 3(based on TTL), 4(inbound + outbound), 5(inbound +based on TTL), 6(outbound + based on TTL), 7(inbound + outbound + based onTTL)")
  public Integer getVccvType() {
    return vccvType;
  }

  public void setVccvType(Integer vccvType) {
    this.vccvType = vccvType;
  }

  public SncPw connAckType(Integer connAckType) {
    this.connAckType = connAckType;
    return this;
  }

  /**
   * 0(None), 1(lsp-ping), 2(lsp-ping+icmp-ping), 3(lsp-ping+bfd-pwach-fs),
   * 4(lsp-ping+bfd-pwach-fo), 5(lsp-ping+bfd-pwach-fs+ bfd-pwach-fo),
   * 6(lsp-ping+icmp-ping+bfd-pwach-fs), 7(lsp-ping+icmp-ping+bfd-pwach-fo),
   * 8(lsp-ping+icmp-ping+bfd-pwach-fs+ bfd-pwach-fo), 9(lsp-ping+bfd-ipudp-fs),
   * 10(lsp-ping+bfd-ipudp-fo), 11(lsp-ping+bfd-ipudp-fs+bfd-ipudp-fo), 12(lsp-ping+icmp-ping
   * +bfd-ipudp-fs), 13(lsp-ping+icmp-ping +bfd-ipudp-fo), 14(lsp-ping+icmp-ping
   * +bfd-ipudp-fs+bfd-ipudp-fo), 15(CCM) minimum: 0.0 maximum: 15.0
   *
   * @return connAckType
   */
  @ApiModelProperty(example = "null",
                    value = "0(None), 1(lsp-ping), 2(lsp-ping+icmp-ping), 3(lsp-ping+bfd-pwach-fs), 4(lsp-ping+bfd-pwach-fo), 5(lsp-ping+bfd-pwach-fs+ bfd-pwach-fo), 6(lsp-ping+icmp-ping+bfd-pwach-fs), 7(lsp-ping+icmp-ping+bfd-pwach-fo), 8(lsp-ping+icmp-ping+bfd-pwach-fs+ bfd-pwach-fo), 9(lsp-ping+bfd-ipudp-fs), 10(lsp-ping+bfd-ipudp-fo), 11(lsp-ping+bfd-ipudp-fs+bfd-ipudp-fo), 12(lsp-ping+icmp-ping +bfd-ipudp-fs), 13(lsp-ping+icmp-ping +bfd-ipudp-fo), 14(lsp-ping+icmp-ping +bfd-ipudp-fs+bfd-ipudp-fo), 15(CCM)")
  public Integer getConnAckType() {
    return connAckType;
  }

  public void setConnAckType(Integer connAckType) {
    this.connAckType = connAckType;
  }

  public SncPw oam(OAM oam) {
    this.oam = oam;
    return this;
  }

  /**
   * Get oam
   *
   * @return oam
   */
  @ApiModelProperty(example = "null", value = "")
  public OAM getOam() {
    return oam;
  }

  public void setOam(OAM oam) {
    this.oam = oam;
  }

  public SncPw qos(QOS qos) {
    this.qos = qos;
    return this;
  }

  /**
   * Get qos
   *
   * @return qos
   */
  @ApiModelProperty(example = "null", value = "")
  public QOS getQos() {
    return qos;
  }

  public void setQos(QOS qos) {
    this.qos = qos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SncPw sncPw = (SncPw) o;
    return Objects.equals(this.id, sncPw.id) &&
           Objects.equals(this.name, sncPw.name) &&
           Objects.equals(this.userLabel, sncPw.userLabel) &&
           Objects.equals(this.role, sncPw.role) &&
           Objects.equals(this.encaplateType, sncPw.encaplateType) &&
           Objects.equals(this.ingressNeId, sncPw.ingressNeId) &&
           Objects.equals(this.egressNeId, sncPw.egressNeId) &&
           Objects.equals(this.sourceIp, sncPw.sourceIp) &&
           Objects.equals(this.destinationIp, sncPw.destinationIp) &&
           Objects.equals(this.tunnelIds, sncPw.tunnelIds) &&
           Objects.equals(this.adminStatus, sncPw.adminStatus) &&
           Objects.equals(this.operateStatus, sncPw.operateStatus) &&
           Objects.equals(this.ctrlWordSupport, sncPw.ctrlWordSupport) &&
           Objects.equals(this.snSupport, sncPw.snSupport) &&
           Objects.equals(this.vccvType, sncPw.vccvType) &&
           Objects.equals(this.connAckType, sncPw.connAckType) &&
           Objects.equals(this.oam, sncPw.oam) &&
           Objects.equals(this.qos, sncPw.qos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, userLabel, role, encaplateType, ingressNeId, egressNeId, sourceIp,
                        destinationIp, tunnelIds, adminStatus, operateStatus, ctrlWordSupport,
                        snSupport, vccvType, connAckType, oam, qos);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SncPw {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    userLabel: ").append(toIndentedString(userLabel)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    encaplateType: ").append(toIndentedString(encaplateType)).append("\n");
    sb.append("    ingressNeId: ").append(toIndentedString(ingressNeId)).append("\n");
    sb.append("    egressNeId: ").append(toIndentedString(egressNeId)).append("\n");
    sb.append("    sourceIp: ").append(toIndentedString(sourceIp)).append("\n");
    sb.append("    destinationIp: ").append(toIndentedString(destinationIp)).append("\n");
    sb.append("    tunnelIds: ").append(toIndentedString(tunnelIds)).append("\n");
    sb.append("    adminStatus: ").append(toIndentedString(adminStatus)).append("\n");
    sb.append("    operateStatus: ").append(toIndentedString(operateStatus)).append("\n");
    sb.append("    ctrlWordSupport: ").append(toIndentedString(ctrlWordSupport)).append("\n");
    sb.append("    snSupport: ").append(toIndentedString(snSupport)).append("\n");
    sb.append("    vccvType: ").append(toIndentedString(vccvType)).append("\n");
    sb.append("    connAckType: ").append(toIndentedString(connAckType)).append("\n");
    sb.append("    oam: ").append(toIndentedString(oam)).append("\n");
    sb.append("    qos: ").append(toIndentedString(qos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

