/**
 * SDN-O SPTN Controller Driver SBI Interface
 * SDN-O SPTN Controller Driver SBI Interface
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.south;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * The route of service
 */
@ApiModel(description = "The route of service")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T10:40:00.335+08:00")
public class SncRoute {

  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("layer-rate")
  private Integer layerRate = null;

  @SerializedName("snc-id")
  private String sncId = null;

  @SerializedName("xcs")
  private List<XC> xcs = new ArrayList<XC>();

  public SncRoute id(String id) {
    this.id = id;
    return this;
  }

  /**
   * UUID of route
   *
   * @return id
   */
  @ApiModelProperty(example = "null", required = true, value = "UUID of route")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SncRoute name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Only used within domain, for driver, it is empty
   *
   * @return name
   */
  @ApiModelProperty(example = "null", value = "Only used within domain, for driver, it is empty")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SncRoute layerRate(Integer layerRate) {
    this.layerRate = layerRate;
    return this;
  }

  /**
   * Layer rate, 0(LSP) or 1(PW)
   *
   * @return layerRate
   */
  @ApiModelProperty(example = "null", value = "Layer rate, 0(LSP) or 1(PW)")
  public Integer getLayerRate() {
    return layerRate;
  }

  public void setLayerRate(Integer layerRate) {
    this.layerRate = layerRate;
  }

  public SncRoute sncId(String sncId) {
    this.sncId = sncId;
    return this;
  }

  /**
   * UUID of service related to the route, LSP ID or PW ID
   *
   * @return sncId
   */
  @ApiModelProperty(example = "null", required = true,
                    value = "UUID of service related to the route, LSP ID or PW ID")
  public String getSncId() {
    return sncId;
  }

  public void setSncId(String sncId) {
    this.sncId = sncId;
  }

  public SncRoute xcs(List<XC> xcs) {
    this.xcs = xcs;
    return this;
  }

  /**
   * Get xcs
   *
   * @return xcs
   */
  @ApiModelProperty(example = "null", value = "")
  public List<XC> getXcs() {
    return xcs;
  }

  public void setXcs(List<XC> xcs) {
    this.xcs = xcs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SncRoute sncRoute = (SncRoute) o;
    return Objects.equals(this.id, sncRoute.id) &&
           Objects.equals(this.name, sncRoute.name) &&
           Objects.equals(this.layerRate, sncRoute.layerRate) &&
           Objects.equals(this.sncId, sncRoute.sncId) &&
           Objects.equals(this.xcs, sncRoute.xcs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, layerRate, sncId, xcs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SncRoute {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    layerRate: ").append(toIndentedString(layerRate)).append("\n");
    sb.append("    sncId: ").append(toIndentedString(sncId)).append("\n");
    sb.append("    xcs: ").append(toIndentedString(xcs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

