/**
 * SDN-O SPTN Controller Driver SBI Interface
 * SDN-O SPTN Controller Driver SBI Interface
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.south;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Policy of create tunnels
 */
@ApiModel(description = "Policy of create tunnels")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T10:40:00.335+08:00")
public class SncTunnelCreatePolicy {

  @SerializedName("Name")
  private String name = null;

  @SerializedName("user-label")
  private String userLabel = null;

  @SerializedName("tenant-Id")
  private String tenantId = null;

  @SerializedName("creater")
  private String creater = null;

  @SerializedName("parent-ncd-id")
  private String parentNcdId = null;

  @SerializedName("direction")
  private Integer direction = null;

  @SerializedName("Type")
  private Integer type = null;

  @SerializedName("qos")
  private QOS qos = null;

  @SerializedName("snc-switch")
  private SncSwitch sncSwitch = null;

  @SerializedName("admin-status")
  private AdminStatus adminStatus = null;

  @SerializedName("lsp-oam")
  private OAM lspOam = null;

  @SerializedName("is-shared")
  private Boolean isShared = false;

  public SncTunnelCreatePolicy name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Only used within domain, for driver, it is empty
   *
   * @return name
   */
  @ApiModelProperty(example = "null", value = "Only used within domain, for driver, it is empty")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SncTunnelCreatePolicy userLabel(String userLabel) {
    this.userLabel = userLabel;
    return this;
  }

  /**
   * User label of tunnel
   *
   * @return userLabel
   */
  @ApiModelProperty(example = "null", required = true, value = "User label of tunnel")
  public String getUserLabel() {
    return userLabel;
  }

  public void setUserLabel(String userLabel) {
    this.userLabel = userLabel;
  }

  public SncTunnelCreatePolicy tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Tenant ID
   *
   * @return tenantId
   */
  @ApiModelProperty(example = "null", value = "Tenant ID")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public SncTunnelCreatePolicy creater(String creater) {
    this.creater = creater;
    return this;
  }

  /**
   * APP ID
   *
   * @return creater
   */
  @ApiModelProperty(example = "null", value = "APP ID")
  public String getCreater() {
    return creater;
  }

  public void setCreater(String creater) {
    this.creater = creater;
  }

  public SncTunnelCreatePolicy parentNcdId(String parentNcdId) {
    this.parentNcdId = parentNcdId;
    return this;
  }

  /**
   * Only used within domain, for driver, it is empty
   *
   * @return parentNcdId
   */
  @ApiModelProperty(example = "null", value = "Only used within domain, for driver, it is empty")
  public String getParentNcdId() {
    return parentNcdId;
  }

  public void setParentNcdId(String parentNcdId) {
    this.parentNcdId = parentNcdId;
  }

  public SncTunnelCreatePolicy direction(Integer direction) {
    this.direction = direction;
    return this;
  }

  /**
   * Direction of tunnel, including 0(unidirection), 1(bidirection)
   *
   * @return direction
   */
  @ApiModelProperty(example = "null",
                    value = "Direction of tunnel, including 0(unidirection), 1(bidirection)")
  public Integer getDirection() {
    return direction;
  }

  public void setDirection(Integer direction) {
    this.direction = direction;
  }

  public SncTunnelCreatePolicy type(Integer type) {
    this.type = type;
    return this;
  }

  /**
   * Type of tunnel, including 1(linear), 2(ring)
   *
   * @return type
   */
  @ApiModelProperty(example = "null", value = "Type of tunnel, including 1(linear), 2(ring)")
  public Integer getType() {
    return type;
  }

  public void setType(Integer type) {
    this.type = type;
  }

  public SncTunnelCreatePolicy qos(QOS qos) {
    this.qos = qos;
    return this;
  }

  /**
   * Get qos
   *
   * @return qos
   */
  @ApiModelProperty(example = "null", value = "")
  public QOS getQos() {
    return qos;
  }

  public void setQos(QOS qos) {
    this.qos = qos;
  }

  public SncTunnelCreatePolicy sncSwitch(SncSwitch sncSwitch) {
    this.sncSwitch = sncSwitch;
    return this;
  }

  /**
   * Get sncSwitch
   *
   * @return sncSwitch
   */
  @ApiModelProperty(example = "null", value = "")
  public SncSwitch getSncSwitch() {
    return sncSwitch;
  }

  public void setSncSwitch(SncSwitch sncSwitch) {
    this.sncSwitch = sncSwitch;
  }

  public SncTunnelCreatePolicy adminStatus(AdminStatus adminStatus) {
    this.adminStatus = adminStatus;
    return this;
  }

  /**
   * Get adminStatus
   *
   * @return adminStatus
   */
  @ApiModelProperty(example = "null", value = "")
  public AdminStatus getAdminStatus() {
    return adminStatus;
  }

  public void setAdminStatus(AdminStatus adminStatus) {
    this.adminStatus = adminStatus;
  }

  public SncTunnelCreatePolicy lspOam(OAM lspOam) {
    this.lspOam = lspOam;
    return this;
  }

  /**
   * Get lspOam
   *
   * @return lspOam
   */
  @ApiModelProperty(example = "null", value = "")
  public OAM getLspOam() {
    return lspOam;
  }

  public void setLspOam(OAM lspOam) {
    this.lspOam = lspOam;
  }

  public SncTunnelCreatePolicy isShared(Boolean isShared) {
    this.isShared = isShared;
    return this;
  }

  /**
   * Whether the tunnel is sharing bandwidth, true(shared), false(not shared)
   *
   * @return isShared
   */
  @ApiModelProperty(example = "null",
                    value = "Whether the tunnel is sharing bandwidth, true(shared), false(not shared)")
  public Boolean getIsShared() {
    return isShared;
  }

  public void setIsShared(Boolean isShared) {
    this.isShared = isShared;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SncTunnelCreatePolicy sncTunnelCreatePolicy = (SncTunnelCreatePolicy) o;
    return Objects.equals(this.name, sncTunnelCreatePolicy.name) &&
           Objects.equals(this.userLabel, sncTunnelCreatePolicy.userLabel) &&
           Objects.equals(this.tenantId, sncTunnelCreatePolicy.tenantId) &&
           Objects.equals(this.creater, sncTunnelCreatePolicy.creater) &&
           Objects.equals(this.parentNcdId, sncTunnelCreatePolicy.parentNcdId) &&
           Objects.equals(this.direction, sncTunnelCreatePolicy.direction) &&
           Objects.equals(this.type, sncTunnelCreatePolicy.type) &&
           Objects.equals(this.qos, sncTunnelCreatePolicy.qos) &&
           Objects.equals(this.sncSwitch, sncTunnelCreatePolicy.sncSwitch) &&
           Objects.equals(this.adminStatus, sncTunnelCreatePolicy.adminStatus) &&
           Objects.equals(this.lspOam, sncTunnelCreatePolicy.lspOam) &&
           Objects.equals(this.isShared, sncTunnelCreatePolicy.isShared);
  }

  @Override
  public int hashCode() {
    return Objects
        .hash(name, userLabel, tenantId, creater, parentNcdId, direction, type, qos, sncSwitch,
              adminStatus, lspOam, isShared);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SncTunnelCreatePolicy {\n");

    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    userLabel: ").append(toIndentedString(userLabel)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    creater: ").append(toIndentedString(creater)).append("\n");
    sb.append("    parentNcdId: ").append(toIndentedString(parentNcdId)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    qos: ").append(toIndentedString(qos)).append("\n");
    sb.append("    sncSwitch: ").append(toIndentedString(sncSwitch)).append("\n");
    sb.append("    adminStatus: ").append(toIndentedString(adminStatus)).append("\n");
    sb.append("    lspOam: ").append(toIndentedString(lspOam)).append("\n");
    sb.append("    isShared: ").append(toIndentedString(isShared)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

