/**
 * SDN-O SPTN Controller Driver SBI Interface
 * SDN-O SPTN Controller Driver SBI Interface
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.south;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * StaticRoute
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T10:40:00.335+08:00")
public class StaticRoute {

  @SerializedName("dest-ip")
  private String destIp = null;

  @SerializedName("dest-mask")
  private String destMask = null;

  @SerializedName("is-backup")
  private Boolean isBackup = null;

  @SerializedName("route-type")
  private Integer routeType = null;

  @SerializedName("next-hop-ip")
  private String nextHopIp = null;

  @SerializedName("out-inf")
  private String outInf = null;

  @SerializedName("route-weight")
  private Integer routeWeight = null;

  @SerializedName("routeStatus")
  private Integer routeStatus = null;

  public StaticRoute destIp(String destIp) {
    this.destIp = destIp;
    return this;
  }

  /**
   * Destination IP address, like \"10.1.1.1\"
   *
   * @return destIp
   */
  @ApiModelProperty(example = "null", value = "Destination IP address, like \"10.1.1.1\"")
  public String getDestIp() {
    return destIp;
  }

  public void setDestIp(String destIp) {
    this.destIp = destIp;
  }

  public StaticRoute destMask(String destMask) {
    this.destMask = destMask;
    return this;
  }

  /**
   * destination IP mask, like \"255.255.0.0\"
   *
   * @return destMask
   */
  @ApiModelProperty(example = "null", value = "destination IP mask, like \"255.255.0.0\"")
  public String getDestMask() {
    return destMask;
  }

  public void setDestMask(String destMask) {
    this.destMask = destMask;
  }

  public StaticRoute isBackup(Boolean isBackup) {
    this.isBackup = isBackup;
    return this;
  }

  /**
   * Whether the route is backup route
   *
   * @return isBackup
   */
  @ApiModelProperty(example = "null", value = "Whether the route is backup route")
  public Boolean getIsBackup() {
    return isBackup;
  }

  public void setIsBackup(Boolean isBackup) {
    this.isBackup = isBackup;
  }

  public StaticRoute routeType(Integer routeType) {
    this.routeType = routeType;
    return this;
  }

  /**
   * Route type, including 0(directly connected route), 1(indirectly connected route), 2(net side
   * route)
   *
   * @return routeType
   */
  @ApiModelProperty(example = "null",
                    value = "Route type, including 0(directly connected route), 1(indirectly connected route), 2(net side route)")
  public Integer getRouteType() {
    return routeType;
  }

  public void setRouteType(Integer routeType) {
    this.routeType = routeType;
  }

  public StaticRoute nextHopIp(String nextHopIp) {
    this.nextHopIp = nextHopIp;
    return this;
  }

  /**
   * Next hop IP address, like \"10.1.1.1\"
   *
   * @return nextHopIp
   */
  @ApiModelProperty(example = "null", value = "Next hop IP address, like \"10.1.1.1\"")
  public String getNextHopIp() {
    return nextHopIp;
  }

  public void setNextHopIp(String nextHopIp) {
    this.nextHopIp = nextHopIp;
  }

  public StaticRoute outInf(String outInf) {
    this.outInf = outInf;
    return this;
  }

  /**
   * out interface(LTP) UUID
   *
   * @return outInf
   */
  @ApiModelProperty(example = "null", value = "out interface(LTP) UUID")
  public String getOutInf() {
    return outInf;
  }

  public void setOutInf(String outInf) {
    this.outInf = outInf;
  }

  public StaticRoute routeWeight(Integer routeWeight) {
    this.routeWeight = routeWeight;
    return this;
  }

  /**
   * Route weight, range from 0 to 255 minimum: 0.0 maximum: 255.0
   *
   * @return routeWeight
   */
  @ApiModelProperty(example = "null", value = "Route weight, range from 0 to 255")
  public Integer getRouteWeight() {
    return routeWeight;
  }

  public void setRouteWeight(Integer routeWeight) {
    this.routeWeight = routeWeight;
  }

  public StaticRoute routeStatus(Integer routeStatus) {
    this.routeStatus = routeStatus;
    return this;
  }

  /**
   * Route Status, including 1(down), 2(up), only used when querying a route
   *
   * @return routeStatus
   */
  @ApiModelProperty(example = "null",
                    value = "Route Status, including 1(down), 2(up), only used when querying a route")
  public Integer getRouteStatus() {
    return routeStatus;
  }

  public void setRouteStatus(Integer routeStatus) {
    this.routeStatus = routeStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StaticRoute staticRoute = (StaticRoute) o;
    return Objects.equals(this.destIp, staticRoute.destIp) &&
           Objects.equals(this.destMask, staticRoute.destMask) &&
           Objects.equals(this.isBackup, staticRoute.isBackup) &&
           Objects.equals(this.routeType, staticRoute.routeType) &&
           Objects.equals(this.nextHopIp, staticRoute.nextHopIp) &&
           Objects.equals(this.outInf, staticRoute.outInf) &&
           Objects.equals(this.routeWeight, staticRoute.routeWeight) &&
           Objects.equals(this.routeStatus, staticRoute.routeStatus);
  }

  @Override
  public int hashCode() {
    return Objects
        .hash(destIp, destMask, isBackup, routeType, nextHopIp, outInf, routeWeight, routeStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StaticRoute {\n");

    sb.append("    destIp: ").append(toIndentedString(destIp)).append("\n");
    sb.append("    destMask: ").append(toIndentedString(destMask)).append("\n");
    sb.append("    isBackup: ").append(toIndentedString(isBackup)).append("\n");
    sb.append("    routeType: ").append(toIndentedString(routeType)).append("\n");
    sb.append("    nextHopIp: ").append(toIndentedString(nextHopIp)).append("\n");
    sb.append("    outInf: ").append(toIndentedString(outInf)).append("\n");
    sb.append("    routeWeight: ").append(toIndentedString(routeWeight)).append("\n");
    sb.append("    routeStatus: ").append(toIndentedString(routeStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

