/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Tunnel policy of Auto select
 */
@ApiModel(description = "Tunnel policy of Auto select")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class AutoSelectPolicy {

  @SerializedName("loadBalanceNumber")
  private Integer loadBalanceNumber = null;

  @SerializedName("autoSelectTunnels")
  private openo.sdno.driver.zte.sptn.models.north.AutoSelectTunnels autoSelectTunnels = null;

  public AutoSelectPolicy loadBalanceNumber(Integer loadBalanceNumber) {
    this.loadBalanceNumber = loadBalanceNumber;
    return this;
  }

  /**
   * Auto Select tunnel Load Number minimum: 1.0 maximum: 32.0
   *
   * @return loadBalanceNumber
   */
  @ApiModelProperty(example = "null", required = true, value = "Auto Select tunnel Load Number")
  public Integer getLoadBalanceNumber() {
    return loadBalanceNumber;
  }

  public void setLoadBalanceNumber(Integer loadBalanceNumber) {
    this.loadBalanceNumber = loadBalanceNumber;
  }

  public AutoSelectPolicy autoSelectTunnels(AutoSelectTunnels autoSelectTunnels) {
    this.autoSelectTunnels = autoSelectTunnels;
    return this;
  }

  /**
   * Get autoSelectTunnels
   *
   * @return autoSelectTunnels
   */
  @ApiModelProperty(example = "null", value = "")
  public AutoSelectTunnels getAutoSelectTunnels() {
    return autoSelectTunnels;
  }

  public void setAutoSelectTunnels(AutoSelectTunnels autoSelectTunnels) {
    this.autoSelectTunnels = autoSelectTunnels;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoSelectPolicy autoSelectPolicy = (AutoSelectPolicy) o;
    return Objects.equals(this.loadBalanceNumber, autoSelectPolicy.loadBalanceNumber) &&
           Objects.equals(this.autoSelectTunnels, autoSelectPolicy.autoSelectTunnels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(loadBalanceNumber, autoSelectTunnels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoSelectPolicy {\n");

    sb.append("    loadBalanceNumber: ").append(toIndentedString(loadBalanceNumber)).append("\n");
    sb.append("    autoSelectTunnels: ").append(toIndentedString(autoSelectTunnels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

