/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Policy Constraints of auto select tunnel policy
 */
@ApiModel(description = "Policy Constraints of auto select tunnel policy")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class AutoSelectTunnel {

  @SerializedName("type")
  private String type = null;

  @SerializedName("priority")
  private Long priority = null;

  public AutoSelectTunnel type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Tunnel type of Auto select tunnel policy
   *
   * @return type
   */
  @ApiModelProperty(example = "null", value = "Tunnel type of Auto select tunnel policy")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public AutoSelectTunnel priority(Long priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Tunnel priority of Auto select tunnel policy
   *
   * @return priority
   */
  @ApiModelProperty(example = "null", value = "Tunnel priority of Auto select tunnel policy")
  public Long getPriority() {
    return priority;
  }

  public void setPriority(Long priority) {
    this.priority = priority;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutoSelectTunnel autoSelectTunnel = (AutoSelectTunnel) o;
    return Objects.equals(this.type, autoSelectTunnel.type) &&
           Objects.equals(this.priority, autoSelectTunnel.priority);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, priority);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutoSelectTunnel {\n");

    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

