/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Bidirectional Forwarding Detection parameter
 */
@ApiModel(description = "Bidirectional Forwarding Detection parameter")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class BfdParameter {

  @SerializedName("minTxInterval")
  private Long minTxInterval = null;

  @SerializedName("minRxInterval")
  private Long minRxInterval = null;

  public BfdParameter minTxInterval(Long minTxInterval) {
    this.minTxInterval = minTxInterval;
    return this;
  }

  /**
   * minTxInterval minimum: 1.0 maximum: 4094.0
   *
   * @return minTxInterval
   */
  @ApiModelProperty(example = "null", value = "minTxInterval")
  public Long getMinTxInterval() {
    return minTxInterval;
  }

  public void setMinTxInterval(Long minTxInterval) {
    this.minTxInterval = minTxInterval;
  }

  public BfdParameter minRxInterval(Long minRxInterval) {
    this.minRxInterval = minRxInterval;
    return this;
  }

  /**
   * minRxInterval minimum: 1.0 maximum: 4094.0
   *
   * @return minRxInterval
   */
  @ApiModelProperty(example = "null", value = "minRxInterval")
  public Long getMinRxInterval() {
    return minRxInterval;
  }

  public void setMinRxInterval(Long minRxInterval) {
    this.minRxInterval = minRxInterval;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BfdParameter bfdParameter = (BfdParameter) o;
    return Objects.equals(this.minTxInterval, bfdParameter.minTxInterval) &&
           Objects.equals(this.minRxInterval, bfdParameter.minRxInterval);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minTxInterval, minRxInterval);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BfdParameter {\n");

    sb.append("    minTxInterval: ").append(toIndentedString(minTxInterval)).append("\n");
    sb.append("    minRxInterval: ").append(toIndentedString(minRxInterval)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

