/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * BGP Route
 */
@ApiModel(description = "BGP Route")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class BgpRoute {

  @SerializedName("remoteAs")
  private String remoteAs = null;

  @SerializedName("localAs")
  private String localAs = null;

  @SerializedName("peerIp")
  private String peerIp = null;

  @SerializedName("localIp")
  private String localIp = null;

  @SerializedName("keepaliveTime")
  private String keepaliveTime = null;

  @SerializedName("holdTime")
  private String holdTime = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("advertiseCommunity")
  private Boolean advertiseCommunity = null;

  @SerializedName("advertiseExtCommunity")
  private Boolean advertiseExtCommunity = null;

  public BgpRoute remoteAs(String remoteAs) {
    this.remoteAs = remoteAs;
    return this;
  }

  /**
   * Remote autonomous system Id
   *
   * @return remoteAs
   */
  @ApiModelProperty(example = "null", required = true, value = "Remote autonomous system Id")
  public String getRemoteAs() {
    return remoteAs;
  }

  public void setRemoteAs(String remoteAs) {
    this.remoteAs = remoteAs;
  }

  public BgpRoute localAs(String localAs) {
    this.localAs = localAs;
    return this;
  }

  /**
   * Local autonomous system Id
   *
   * @return localAs
   */
  @ApiModelProperty(example = "null", value = "Local autonomous system Id")
  public String getLocalAs() {
    return localAs;
  }

  public void setLocalAs(String localAs) {
    this.localAs = localAs;
  }

  public BgpRoute peerIp(String peerIp) {
    this.peerIp = peerIp;
    return this;
  }

  /**
   * Peer IpAddress
   *
   * @return peerIp
   */
  @ApiModelProperty(example = "null", required = true, value = "Peer IpAddress")
  public String getPeerIp() {
    return peerIp;
  }

  public void setPeerIp(String peerIp) {
    this.peerIp = peerIp;
  }

  public BgpRoute localIp(String localIp) {
    this.localIp = localIp;
    return this;
  }

  /**
   * Local IpAddress
   *
   * @return localIp
   */
  @ApiModelProperty(example = "null", value = "Local IpAddress")
  public String getLocalIp() {
    return localIp;
  }

  public void setLocalIp(String localIp) {
    this.localIp = localIp;
  }

  public BgpRoute keepaliveTime(String keepaliveTime) {
    this.keepaliveTime = keepaliveTime;
    return this;
  }

  /**
   * Time of keeping alive
   *
   * @return keepaliveTime
   */
  @ApiModelProperty(example = "null", value = "Time of keeping alive")
  public String getKeepaliveTime() {
    return keepaliveTime;
  }

  public void setKeepaliveTime(String keepaliveTime) {
    this.keepaliveTime = keepaliveTime;
  }

  public BgpRoute holdTime(String holdTime) {
    this.holdTime = holdTime;
    return this;
  }

  /**
   * Time of holding
   *
   * @return holdTime
   */
  @ApiModelProperty(example = "null", value = "Time of holding")
  public String getHoldTime() {
    return holdTime;
  }

  public void setHoldTime(String holdTime) {
    this.holdTime = holdTime;
  }

  public BgpRoute password(String password) {
    this.password = password;
    return this;
  }

  /**
   * password
   *
   * @return password
   */
  @ApiModelProperty(example = "null", value = "password")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public BgpRoute advertiseCommunity(Boolean advertiseCommunity) {
    this.advertiseCommunity = advertiseCommunity;
    return this;
  }

  /**
   * Whether to advertise community (true, false)
   *
   * @return advertiseCommunity
   */
  @ApiModelProperty(example = "null", value = "Whether to advertise community (true, false)")
  public Boolean getAdvertiseCommunity() {
    return advertiseCommunity;
  }

  public void setAdvertiseCommunity(Boolean advertiseCommunity) {
    this.advertiseCommunity = advertiseCommunity;
  }

  public BgpRoute advertiseExtCommunity(Boolean advertiseExtCommunity) {
    this.advertiseExtCommunity = advertiseExtCommunity;
    return this;
  }

  /**
   * Whether to advertise external community (true, false)
   *
   * @return advertiseExtCommunity
   */
  @ApiModelProperty(example = "null",
                    value = "Whether to advertise external community (true, false)")
  public Boolean getAdvertiseExtCommunity() {
    return advertiseExtCommunity;
  }

  public void setAdvertiseExtCommunity(Boolean advertiseExtCommunity) {
    this.advertiseExtCommunity = advertiseExtCommunity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BgpRoute bgpRoute = (BgpRoute) o;
    return Objects.equals(this.remoteAs, bgpRoute.remoteAs) &&
           Objects.equals(this.localAs, bgpRoute.localAs) &&
           Objects.equals(this.peerIp, bgpRoute.peerIp) &&
           Objects.equals(this.localIp, bgpRoute.localIp) &&
           Objects.equals(this.keepaliveTime, bgpRoute.keepaliveTime) &&
           Objects.equals(this.holdTime, bgpRoute.holdTime) &&
           Objects.equals(this.password, bgpRoute.password) &&
           Objects.equals(this.advertiseCommunity, bgpRoute.advertiseCommunity) &&
           Objects.equals(this.advertiseExtCommunity, bgpRoute.advertiseExtCommunity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(remoteAs, localAs, peerIp, localIp, keepaliveTime, holdTime, password,
                        advertiseCommunity, advertiseExtCommunity);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BgpRoute {\n");

    sb.append("    remoteAs: ").append(toIndentedString(remoteAs)).append("\n");
    sb.append("    localAs: ").append(toIndentedString(localAs)).append("\n");
    sb.append("    peerIp: ").append(toIndentedString(peerIp)).append("\n");
    sb.append("    localIp: ").append(toIndentedString(localIp)).append("\n");
    sb.append("    keepaliveTime: ").append(toIndentedString(keepaliveTime)).append("\n");
    sb.append("    holdTime: ").append(toIndentedString(holdTime)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    advertiseCommunity: ").append(toIndentedString(advertiseCommunity)).append("\n");
    sb.append("    advertiseExtCommunity: ").append(toIndentedString(advertiseExtCommunity))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

