/**
 * L2VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L2VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * L2Ac
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-07-27T16:44:16.967+08:00")
public class L2Ac {

  @SerializedName("externalQosPolicyId")
  private String externalQosPolicyId = null;

  @SerializedName("overrideFlows")
  private OverrideFlows overrideFlows = null;

  public L2Ac externalQosPolicyId(String externalQosPolicyId) {
    this.externalQosPolicyId = externalQosPolicyId;
    return this;
  }

  /**
   * Id of External Qos Policy
   *
   * @return externalQosPolicyId
   */
  @ApiModelProperty(example = "null", required = true, value = "Id of External Qos Policy")
  public String getExternalQosPolicyId() {
    return externalQosPolicyId;
  }

  public void setExternalQosPolicyId(String externalQosPolicyId) {
    this.externalQosPolicyId = externalQosPolicyId;
  }

  public L2Ac overrideFlows(OverrideFlows overrideFlows) {
    this.overrideFlows = overrideFlows;
    return this;
  }

  /**
   * Get overrideFlows
   *
   * @return overrideFlows
   */
  @ApiModelProperty(example = "null", value = "")
  public OverrideFlows getOverrideFlows() {
    return overrideFlows;
  }

  public void setOverrideFlows(OverrideFlows overrideFlows) {
    this.overrideFlows = overrideFlows;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    L2Ac l2Ac = (L2Ac) o;
    return Objects.equals(this.externalQosPolicyId, l2Ac.externalQosPolicyId) &&
           Objects.equals(this.overrideFlows, l2Ac.overrideFlows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalQosPolicyId, overrideFlows);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class L2Ac {\n");

    sb.append("    externalQosPolicyId: ").append(toIndentedString(externalQosPolicyId))
        .append("\n");
    sb.append("    overrideFlows: ").append(toIndentedString(overrideFlows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

