/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * L3Vpn Access point configuration
 */
@ApiModel(description = "L3Vpn Access point configuration")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class L3Ac {

  @SerializedName("id")
  private String id = null;

  @SerializedName("neId")
  private String neId = null;

  @SerializedName("ltpId")
  private String ltpId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("localName")
  private String localName = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("adminStatus")
  private String adminStatus = null;

  @SerializedName("operStatus")
  private String operStatus = null;

  @SerializedName("upstreamBandwidth")
  private QosIfCar upstreamBandwidth = null;

  @SerializedName("downstreamBandwidth")
  private QosIfCar downstreamBandwidth = null;

  @SerializedName("l2Access")
  private L2Access l2Access = null;

  @SerializedName("l3Access")
  private L3Access l3Access = null;

  @SerializedName("inboundQosPolicyId")
  private String inboundQosPolicyId = null;

  @SerializedName("outboundQosPolicyId")
  private String outboundQosPolicyId = null;

  @SerializedName("inboundQueuePolicyId")
  private String inboundQueuePolicyId = null;

  @SerializedName("outboundQueuePolicyId")
  private String outboundQueuePolicyId = null;

  @SerializedName("externalQosPolicyId")
  private String externalQosPolicyId = null;

  @SerializedName("overrideFlows")
  private OverrideFlows overrideFlows = null;

  public L3Ac id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Ac ID
   *
   * @return id
   */
  @ApiModelProperty(example = "null", required = true, value = "Ac ID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public L3Ac neId(String neId) {
    this.neId = neId;
    return this;
  }

  /**
   * Network Element Device Id
   *
   * @return neId
   */
  @ApiModelProperty(example = "null", required = true, value = "Network Element Device Id")
  public String getNeId() {
    return neId;
  }

  public void setNeId(String neId) {
    this.neId = neId;
  }

  public L3Ac ltpId(String ltpId) {
    this.ltpId = ltpId;
    return this;
  }

  /**
   * Ltp Id
   *
   * @return ltpId
   */
  @ApiModelProperty(example = "null", required = true, value = "Ltp Id")
  public String getLtpId() {
    return ltpId;
  }

  public void setLtpId(String ltpId) {
    this.ltpId = ltpId;
  }

  public L3Ac name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Ac name
   *
   * @return name
   */
  @ApiModelProperty(example = "null", required = true, value = "Ac name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public L3Ac localName(String localName) {
    this.localName = localName;
    return this;
  }

  /**
   * Local name.
   *
   * @return localName
   */
  @ApiModelProperty(example = "null", value = "Local name.")
  public String getLocalName() {
    return localName;
  }

  public void setLocalName(String localName) {
    this.localName = localName;
  }

  public L3Ac tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * Tenant Id
   *
   * @return tenantId
   */
  @ApiModelProperty(example = "null", required = true, value = "Tenant Id")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public L3Ac description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Ac description
   *
   * @return description
   */
  @ApiModelProperty(example = "null", value = "Ac description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public L3Ac adminStatus(String adminStatus) {
    this.adminStatus = adminStatus;
    return this;
  }

  /**
   * management status(active, inactive). Active - activate the Ac; Inactive - inactivate the Ac.
   * adminUp(0, \"adminUp\"), adminDown(1, \"adminDown\");
   *
   * @return adminStatus
   */
  @ApiModelProperty(example = "null", required = true,
                    value = "management status(active, inactive). Active - activate the Ac; Inactive - inactivate the Ac. adminUp(0, \"adminUp\"), adminDown(1, \"adminDown\");")
  public String getAdminStatus() {
    return adminStatus;
  }

  public void setAdminStatus(String adminStatus) {
    this.adminStatus = adminStatus;
  }

  public L3Ac operStatus(String operStatus) {
    this.operStatus = operStatus;
    return this;
  }

  /**
   * The running status of Ac (up,down,partially down). operateUp(0, \"operateUp\"), operateDown(1,
   * \"operateDown\");
   *
   * @return operStatus
   */
  @ApiModelProperty(example = "null",
                    value = "The running status of Ac (up,down,partially down). operateUp(0, \"operateUp\"), operateDown(1, \"operateDown\");")
  public String getOperStatus() {
    return operStatus;
  }

  public void setOperStatus(String operStatus) {
    this.operStatus = operStatus;
  }

  public L3Ac upstreamBandwidth(QosIfCar upstreamBandwidth) {
    this.upstreamBandwidth = upstreamBandwidth;
    return this;
  }

  /**
   * Get upstreamBandwidth
   *
   * @return upstreamBandwidth
   */
  @ApiModelProperty(example = "null", value = "")
  public QosIfCar getUpstreamBandwidth() {
    return upstreamBandwidth;
  }

  public void setUpstreamBandwidth(QosIfCar upstreamBandwidth) {
    this.upstreamBandwidth = upstreamBandwidth;
  }

  public L3Ac downstreamBandwidth(QosIfCar downstreamBandwidth) {
    this.downstreamBandwidth = downstreamBandwidth;
    return this;
  }

  /**
   * Get downstreamBandwidth
   *
   * @return downstreamBandwidth
   */
  @ApiModelProperty(example = "null", value = "")
  public QosIfCar getDownstreamBandwidth() {
    return downstreamBandwidth;
  }

  public void setDownstreamBandwidth(QosIfCar downstreamBandwidth) {
    this.downstreamBandwidth = downstreamBandwidth;
  }

  public L3Ac l2Access(L2Access l2Access) {
    this.l2Access = l2Access;
    return this;
  }

  /**
   * Get l2Access
   *
   * @return l2Access
   */
  @ApiModelProperty(example = "null", value = "")
  public L2Access getL2Access() {
    return l2Access;
  }

  public void setL2Access(L2Access l2Access) {
    this.l2Access = l2Access;
  }

  public L3Ac l3Access(L3Access l3Access) {
    this.l3Access = l3Access;
    return this;
  }

  /**
   * Get l3Access
   *
   * @return l3Access
   */
  @ApiModelProperty(example = "null", value = "")
  public L3Access getL3Access() {
    return l3Access;
  }

  public void setL3Access(L3Access l3Access) {
    this.l3Access = l3Access;
  }

  public L3Ac inboundQosPolicyId(String inboundQosPolicyId) {
    this.inboundQosPolicyId = inboundQosPolicyId;
    return this;
  }

  /**
   * Id of Inbound Qos Policy
   *
   * @return inboundQosPolicyId
   */
  @ApiModelProperty(example = "null", value = "Id of Inbound Qos Policy")
  public String getInboundQosPolicyId() {
    return inboundQosPolicyId;
  }

  public void setInboundQosPolicyId(String inboundQosPolicyId) {
    this.inboundQosPolicyId = inboundQosPolicyId;
  }

  public L3Ac outboundQosPolicyId(String outboundQosPolicyId) {
    this.outboundQosPolicyId = outboundQosPolicyId;
    return this;
  }

  /**
   * Id of Outbound Qos Policy
   *
   * @return outboundQosPolicyId
   */
  @ApiModelProperty(example = "null", value = "Id of Outbound Qos Policy")
  public String getOutboundQosPolicyId() {
    return outboundQosPolicyId;
  }

  public void setOutboundQosPolicyId(String outboundQosPolicyId) {
    this.outboundQosPolicyId = outboundQosPolicyId;
  }

  public L3Ac inboundQueuePolicyId(String inboundQueuePolicyId) {
    this.inboundQueuePolicyId = inboundQueuePolicyId;
    return this;
  }

  /**
   * Id of Inbound Queue Qos Policy
   *
   * @return inboundQueuePolicyId
   */
  @ApiModelProperty(example = "null", value = "Id of Inbound Queue Qos Policy")
  public String getInboundQueuePolicyId() {
    return inboundQueuePolicyId;
  }

  public void setInboundQueuePolicyId(String inboundQueuePolicyId) {
    this.inboundQueuePolicyId = inboundQueuePolicyId;
  }

  public L3Ac outboundQueuePolicyId(String outboundQueuePolicyId) {
    this.outboundQueuePolicyId = outboundQueuePolicyId;
    return this;
  }

  /**
   * Id of Outbound Queue Qos Policy
   *
   * @return outboundQueuePolicyId
   */
  @ApiModelProperty(example = "null", value = "Id of Outbound Queue Qos Policy")
  public String getOutboundQueuePolicyId() {
    return outboundQueuePolicyId;
  }

  public void setOutboundQueuePolicyId(String outboundQueuePolicyId) {
    this.outboundQueuePolicyId = outboundQueuePolicyId;
  }

  public L3Ac externalQosPolicyId(String externalQosPolicyId) {
    this.externalQosPolicyId = externalQosPolicyId;
    return this;
  }

  /**
   * Id of External Qos Policy
   *
   * @return externalQosPolicyId
   */
  @ApiModelProperty(example = "null", value = "Id of External Qos Policy")
  public String getExternalQosPolicyId() {
    return externalQosPolicyId;
  }

  public void setExternalQosPolicyId(String externalQosPolicyId) {
    this.externalQosPolicyId = externalQosPolicyId;
  }

  public L3Ac overrideFlows(OverrideFlows overrideFlows) {
    this.overrideFlows = overrideFlows;
    return this;
  }

  /**
   * Get overrideFlows
   *
   * @return overrideFlows
   */
  @ApiModelProperty(example = "null", value = "")
  public OverrideFlows getOverrideFlows() {
    return overrideFlows;
  }

  public void setOverrideFlows(OverrideFlows overrideFlows) {
    this.overrideFlows = overrideFlows;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    L3Ac l3Ac = (L3Ac) o;
    return Objects.equals(this.id, l3Ac.id) &&
           Objects.equals(this.neId, l3Ac.neId) &&
           Objects.equals(this.ltpId, l3Ac.ltpId) &&
           Objects.equals(this.name, l3Ac.name) &&
           Objects.equals(this.localName, l3Ac.localName) &&
           Objects.equals(this.tenantId, l3Ac.tenantId) &&
           Objects.equals(this.description, l3Ac.description) &&
           Objects.equals(this.adminStatus, l3Ac.adminStatus) &&
           Objects.equals(this.operStatus, l3Ac.operStatus) &&
           Objects.equals(this.upstreamBandwidth, l3Ac.upstreamBandwidth) &&
           Objects.equals(this.downstreamBandwidth, l3Ac.downstreamBandwidth) &&
           Objects.equals(this.l2Access, l3Ac.l2Access) &&
           Objects.equals(this.l3Access, l3Ac.l3Access) &&
           Objects.equals(this.inboundQosPolicyId, l3Ac.inboundQosPolicyId) &&
           Objects.equals(this.outboundQosPolicyId, l3Ac.outboundQosPolicyId) &&
           Objects.equals(this.inboundQueuePolicyId, l3Ac.inboundQueuePolicyId) &&
           Objects.equals(this.outboundQueuePolicyId, l3Ac.outboundQueuePolicyId) &&
           Objects.equals(this.externalQosPolicyId, l3Ac.externalQosPolicyId) &&
           Objects.equals(this.overrideFlows, l3Ac.overrideFlows);
  }

  @Override
  public int hashCode() {
    return Objects
        .hash(id, neId, ltpId, name, localName, tenantId, description, adminStatus, operStatus,
              upstreamBandwidth, downstreamBandwidth, l2Access, l3Access, inboundQosPolicyId,
              outboundQosPolicyId, inboundQueuePolicyId, outboundQueuePolicyId, externalQosPolicyId,
              overrideFlows);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class L3Ac {\n");

    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    neId: ").append(toIndentedString(neId)).append("\n");
    sb.append("    ltpId: ").append(toIndentedString(ltpId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    localName: ").append(toIndentedString(localName)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    adminStatus: ").append(toIndentedString(adminStatus)).append("\n");
    sb.append("    operStatus: ").append(toIndentedString(operStatus)).append("\n");
    sb.append("    upstreamBandwidth: ").append(toIndentedString(upstreamBandwidth)).append("\n");
    sb.append("    downstreamBandwidth: ").append(toIndentedString(downstreamBandwidth))
        .append("\n");
    sb.append("    l2Access: ").append(toIndentedString(l2Access)).append("\n");
    sb.append("    l3Access: ").append(toIndentedString(l3Access)).append("\n");
    sb.append("    inboundQosPolicyId: ").append(toIndentedString(inboundQosPolicyId)).append("\n");
    sb.append("    outboundQosPolicyId: ").append(toIndentedString(outboundQosPolicyId))
        .append("\n");
    sb.append("    inboundQueuePolicyId: ").append(toIndentedString(inboundQueuePolicyId))
        .append("\n");
    sb.append("    outboundQueuePolicyId: ").append(toIndentedString(outboundQueuePolicyId))
        .append("\n");
    sb.append("    externalQosPolicyId: ").append(toIndentedString(externalQosPolicyId))
        .append("\n");
    sb.append("    overrideFlows: ").append(toIndentedString(overrideFlows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

