/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * a general structure for response
 */
@ApiModel(description = "a general structure for response")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class L3VpnResponse {

  @SerializedName("ret")
  private Integer ret = null;

  @SerializedName("format")
  private String format = null;

  @SerializedName("msg")
  private String msg = null;

  @SerializedName("success")
  private Boolean success = null;

  @SerializedName("respHeaders")
  private Map<String, String> respHeaders = new HashMap<String, String>();

  public L3VpnResponse ret(Integer ret) {
    this.ret = ret;
    return this;
  }

  /**
   * Http Status code of controller
   *
   * @return ret
   */
  @ApiModelProperty(example = "null", required = true, value = "Http Status code of controller")
  public Integer getRet() {
    return ret;
  }

  public void setRet(Integer ret) {
    this.ret = ret;
  }

  public L3VpnResponse format(String format) {
    this.format = format;
    return this;
  }

  /**
   * Return data format,such as \"json\"
   *
   * @return format
   */
  @ApiModelProperty(example = "null", required = true,
                    value = "Return data format,such as \"json\"")
  public String getFormat() {
    return format;
  }

  public void setFormat(String format) {
    this.format = format;
  }

  public L3VpnResponse msg(String msg) {
    this.msg = msg;
    return this;
  }

  /**
   * Response msg returned from adapter
   *
   * @return msg
   */
  @ApiModelProperty(example = "null", value = "Response msg returned from adapter")
  public String getMsg() {
    return msg;
  }

  public void setMsg(String msg) {
    this.msg = msg;
  }

  public L3VpnResponse success(Boolean success) {
    this.success = success;
    return this;
  }

  /**
   * Whether is success
   *
   * @return success
   */
  @ApiModelProperty(example = "null", value = "Whether is success")
  public Boolean getSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public L3VpnResponse respHeaders(Map<String, String> respHeaders) {
    this.respHeaders = respHeaders;
    return this;
  }

  /**
   * Response headers
   *
   * @return respHeaders
   */
  @ApiModelProperty(example = "null", value = "Response headers")
  public Map<String, String> getRespHeaders() {
    return respHeaders;
  }

  public void setRespHeaders(Map<String, String> respHeaders) {
    this.respHeaders = respHeaders;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    L3VpnResponse l3VpnResponse = (L3VpnResponse) o;
    return Objects.equals(this.ret, l3VpnResponse.ret) &&
           Objects.equals(this.format, l3VpnResponse.format) &&
           Objects.equals(this.msg, l3VpnResponse.msg) &&
           Objects.equals(this.success, l3VpnResponse.success) &&
           Objects.equals(this.respHeaders, l3VpnResponse.respHeaders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ret, format, msg, success, respHeaders);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class L3VpnResponse {\n");

    sb.append("    ret: ").append(toIndentedString(ret)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    respHeaders: ").append(toIndentedString(respHeaders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

