/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * List of Ospf Route
 */
@ApiModel(description = "List of Ospf Route")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class OspfRoutes {

  @SerializedName("ospfRoute")
  private List<OspfRoute> ospfRoute = new ArrayList<OspfRoute>();

  public OspfRoutes ospfRoute(List<OspfRoute> ospfRoute) {
    this.ospfRoute = ospfRoute;
    return this;
  }

  /**
   * Get ospfRoute
   *
   * @return ospfRoute
   */
  @ApiModelProperty(example = "null", required = true, value = "")
  public List<OspfRoute> getOspfRoute() {
    return ospfRoute;
  }

  public void setOspfRoute(List<OspfRoute> ospfRoute) {
    this.ospfRoute = ospfRoute;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OspfRoutes ospfRoutes = (OspfRoutes) o;
    return Objects.equals(this.ospfRoute, ospfRoutes.ospfRoute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ospfRoute);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OspfRoutes {\n");

    sb.append("    ospfRoute: ").append(toIndentedString(ospfRoute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

