/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Constraints of Tunnel route
 */
@ApiModel(description = "Constraints of Tunnel route")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class PathConstraint {

  @SerializedName("setupPriority")
  private Long setupPriority = null;

  @SerializedName("holdupPriority")
  private Long holdupPriority = null;

  @SerializedName("latency")
  private Long latency = null;

  public PathConstraint setupPriority(Long setupPriority) {
    this.setupPriority = setupPriority;
    return this;
  }

  /**
   * Setup priority of tunnel route constraints minimum: 0.0 maximum: 7.0
   *
   * @return setupPriority
   */
  @ApiModelProperty(example = "null", value = "Setup priority of tunnel route constraints")
  public Long getSetupPriority() {
    return setupPriority;
  }

  public void setSetupPriority(Long setupPriority) {
    this.setupPriority = setupPriority;
  }

  public PathConstraint holdupPriority(Long holdupPriority) {
    this.holdupPriority = holdupPriority;
    return this;
  }

  /**
   * Holdup priority of tunnel route constraints minimum: 0.0 maximum: 7.0
   *
   * @return holdupPriority
   */
  @ApiModelProperty(example = "null", value = "Holdup priority of tunnel route constraints")
  public Long getHoldupPriority() {
    return holdupPriority;
  }

  public void setHoldupPriority(Long holdupPriority) {
    this.holdupPriority = holdupPriority;
  }

  public PathConstraint latency(Long latency) {
    this.latency = latency;
    return this;
  }

  /**
   * Latency priority of tunnel route constraints minimum: 0.0 maximum: 6.0E7
   *
   * @return latency
   */
  @ApiModelProperty(example = "null", value = "Latency priority of tunnel route constraints")
  public Long getLatency() {
    return latency;
  }

  public void setLatency(Long latency) {
    this.latency = latency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PathConstraint pathConstraint = (PathConstraint) o;
    return Objects.equals(this.setupPriority, pathConstraint.setupPriority) &&
           Objects.equals(this.holdupPriority, pathConstraint.holdupPriority) &&
           Objects.equals(this.latency, pathConstraint.latency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(setupPriority, holdupPriority, latency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PathConstraint {\n");

    sb.append("    setupPriority: ").append(toIndentedString(setupPriority)).append("\n");
    sb.append("    holdupPriority: ").append(toIndentedString(holdupPriority)).append("\n");
    sb.append("    latency: ").append(toIndentedString(latency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

