/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Tunnel protection policy
 */
@ApiModel(description = "Tunnel protection policy")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class PathProtectPolicy {

  @SerializedName("type")
  private String type = null;

  @SerializedName("hotStandbyEnable")
  private Boolean hotStandbyEnable = null;

  @SerializedName("retrieve")
  private Boolean retrieve = null;

  @SerializedName("bandwidthMode")
  private String bandwidthMode = null;

  @SerializedName("wtr")
  private Integer wtr = null;

  public PathProtectPolicy type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Type of tunnel protection policy
   *
   * @return type
   */
  @ApiModelProperty(example = "null", required = true, value = "Type of tunnel protection policy")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public PathProtectPolicy hotStandbyEnable(Boolean hotStandbyEnable) {
    this.hotStandbyEnable = hotStandbyEnable;
    return this;
  }

  /**
   * Whether to enable hotstandby in tunnel protection (true, false)
   *
   * @return hotStandbyEnable
   */
  @ApiModelProperty(example = "null",
                    value = "Whether to enable hotstandby in tunnel protection (true, false)")
  public Boolean getHotStandbyEnable() {
    return hotStandbyEnable;
  }

  public void setHotStandbyEnable(Boolean hotStandbyEnable) {
    this.hotStandbyEnable = hotStandbyEnable;
  }

  public PathProtectPolicy retrieve(Boolean retrieve) {
    this.retrieve = retrieve;
    return this;
  }

  /**
   * Whether to revertive in tunnel protection (true, false)
   *
   * @return retrieve
   */
  @ApiModelProperty(example = "null",
                    value = "Whether to revertive in tunnel protection (true, false)")
  public Boolean getRetrieve() {
    return retrieve;
  }

  public void setRetrieve(Boolean retrieve) {
    this.retrieve = retrieve;
  }

  public PathProtectPolicy bandwidthMode(String bandwidthMode) {
    this.bandwidthMode = bandwidthMode;
    return this;
  }

  /**
   * Bandwidth mode of tunnel protection. (original-bandwidth, dynamic-bandwidth)
   *
   * @return bandwidthMode
   */
  @ApiModelProperty(example = "null",
                    value = "Bandwidth mode of tunnel protection. (original-bandwidth, dynamic-bandwidth)")
  public String getBandwidthMode() {
    return bandwidthMode;
  }

  public void setBandwidthMode(String bandwidthMode) {
    this.bandwidthMode = bandwidthMode;
  }

  public PathProtectPolicy wtr(Integer wtr) {
    this.wtr = wtr;
    return this;
  }

  /**
   * Wtr time of tunnel protection revertive in micro-second minimum: 0.0 maximum: 6.0E7
   *
   * @return wtr
   */
  @ApiModelProperty(example = "null",
                    value = "Wtr time of tunnel protection revertive in micro-second")
  public Integer getWtr() {
    return wtr;
  }

  public void setWtr(Integer wtr) {
    this.wtr = wtr;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PathProtectPolicy pathProtectPolicy = (PathProtectPolicy) o;
    return Objects.equals(this.type, pathProtectPolicy.type) &&
           Objects.equals(this.hotStandbyEnable, pathProtectPolicy.hotStandbyEnable) &&
           Objects.equals(this.retrieve, pathProtectPolicy.retrieve) &&
           Objects.equals(this.bandwidthMode, pathProtectPolicy.bandwidthMode) &&
           Objects.equals(this.wtr, pathProtectPolicy.wtr);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, hotStandbyEnable, retrieve, bandwidthMode, wtr);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PathProtectPolicy {\n");

    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    hotStandbyEnable: ").append(toIndentedString(hotStandbyEnable)).append("\n");
    sb.append("    retrieve: ").append(toIndentedString(retrieve)).append("\n");
    sb.append("    bandwidthMode: ").append(toIndentedString(bandwidthMode)).append("\n");
    sb.append("    wtr: ").append(toIndentedString(wtr)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

