/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * protection group
 */
@ApiModel(description = "protection group")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class ProtectGroup {

  @SerializedName("masterAc")
  private String masterAc = null;

  @SerializedName("backupAc")
  private String backupAc = null;

  @SerializedName("vrrp")
  private Vrrp vrrp = null;

  public ProtectGroup masterAc(String masterAc) {
    this.masterAc = masterAc;
    return this;
  }

  /**
   * The master id of AC protect group
   *
   * @return masterAc
   */
  @ApiModelProperty(example = "null", value = "The master id of AC protect group")
  public String getMasterAc() {
    return masterAc;
  }

  public void setMasterAc(String masterAc) {
    this.masterAc = masterAc;
  }

  public ProtectGroup backupAc(String backupAc) {
    this.backupAc = backupAc;
    return this;
  }

  /**
   * The backup id of AC protect group
   *
   * @return backupAc
   */
  @ApiModelProperty(example = "null", value = "The backup id of AC protect group")
  public String getBackupAc() {
    return backupAc;
  }

  public void setBackupAc(String backupAc) {
    this.backupAc = backupAc;
  }

  public ProtectGroup vrrp(Vrrp vrrp) {
    this.vrrp = vrrp;
    return this;
  }

  /**
   * Get vrrp
   *
   * @return vrrp
   */
  @ApiModelProperty(example = "null", value = "")
  public Vrrp getVrrp() {
    return vrrp;
  }

  public void setVrrp(Vrrp vrrp) {
    this.vrrp = vrrp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProtectGroup protectGroup = (ProtectGroup) o;
    return Objects.equals(this.masterAc, protectGroup.masterAc) &&
           Objects.equals(this.backupAc, protectGroup.backupAc) &&
           Objects.equals(this.vrrp, protectGroup.vrrp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(masterAc, backupAc, vrrp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProtectGroup {\n");

    sb.append("    masterAc: ").append(toIndentedString(masterAc)).append("\n");
    sb.append("    backupAc: ").append(toIndentedString(backupAc)).append("\n");
    sb.append("    vrrp: ").append(toIndentedString(vrrp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

