/**
 * L2VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L2VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;


/**
 * Pw
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-07-27T16:44:16.967+08:00")
public class Pw {

  @SerializedName("uuid")
  private String uuid = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("tenantId")
  private String tenantId = null;

  @SerializedName("neId")
  private String neId = null;

  @SerializedName("peerAddress")
  private String peerAddress = null;

  @SerializedName("tunnelId")
  private String tunnelId = null;

  @SerializedName("topoRole")
  private String topoRole = null;

  @SerializedName("protectionRole")
  private String protectionRole = null;

  public Pw uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

  /**
   * uuid of private wire
   *
   * @return uuid
   */
  @ApiModelProperty(example = "null", required = true, value = "uuid of private wire")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public Pw name(String name) {
    this.name = name;
    return this;
  }

  /**
   * name of private wire
   *
   * @return name
   */
  @ApiModelProperty(example = "null", value = "name of private wire")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Pw description(String description) {
    this.description = description;
    return this;
  }

  /**
   * description of private wire
   *
   * @return description
   */
  @ApiModelProperty(example = "null", value = "description of private wire")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Pw tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

  /**
   * tenant uuid
   *
   * @return tenantId
   */
  @ApiModelProperty(example = "null", value = "tenant uuid")
  public String getTenantId() {
    return tenantId;
  }

  public void setTenantId(String tenantId) {
    this.tenantId = tenantId;
  }

  public Pw neId(String neId) {
    this.neId = neId;
    return this;
  }

  /**
   * real device uuid allocated by sdno
   *
   * @return neId
   */
  @ApiModelProperty(example = "null", value = "real device uuid allocated by sdno")
  public String getNeId() {
    return neId;
  }

  public void setNeId(String neId) {
    this.neId = neId;
  }

  public Pw peerAddress(String peerAddress) {
    this.peerAddress = peerAddress;
    return this;
  }

  /**
   * remote ipaddress
   *
   * @return peerAddress
   */
  @ApiModelProperty(example = "null", value = "remote ipaddress")
  public String getPeerAddress() {
    return peerAddress;
  }

  public void setPeerAddress(String peerAddress) {
    this.peerAddress = peerAddress;
  }

  public Pw tunnelId(String tunnelId) {
    this.tunnelId = tunnelId;
    return this;
  }

  /**
   * tunnel id
   *
   * @return tunnelId
   */
  @ApiModelProperty(example = "null", value = "tunnel id")
  public String getTunnelId() {
    return tunnelId;
  }

  public void setTunnelId(String tunnelId) {
    this.tunnelId = tunnelId;
  }

  public Pw topoRole(String topoRole) {
    this.topoRole = topoRole;
    return this;
  }

  /**
   * topology role, including hub, spoke
   *
   * @return topoRole
   */
  @ApiModelProperty(example = "null", value = "topology role, including hub, spoke")
  public String getTopoRole() {
    return topoRole;
  }

  public void setTopoRole(String topoRole) {
    this.topoRole = topoRole;
  }

  public Pw protectionRole(String protectionRole) {
    this.protectionRole = protectionRole;
    return this;
  }

  /**
   * protection role, including primary, backup
   *
   * @return protectionRole
   */
  @ApiModelProperty(example = "null", value = "protection role, including primary, backup")
  public String getProtectionRole() {
    return protectionRole;
  }

  public void setProtectionRole(String protectionRole) {
    this.protectionRole = protectionRole;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pw pw = (Pw) o;
    return Objects.equals(this.uuid, pw.uuid) &&
           Objects.equals(this.name, pw.name) &&
           Objects.equals(this.description, pw.description) &&
           Objects.equals(this.tenantId, pw.tenantId) &&
           Objects.equals(this.neId, pw.neId) &&
           Objects.equals(this.peerAddress, pw.peerAddress) &&
           Objects.equals(this.tunnelId, pw.tunnelId) &&
           Objects.equals(this.topoRole, pw.topoRole) &&
           Objects.equals(this.protectionRole, pw.protectionRole);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, name, description, tenantId, neId, peerAddress, tunnelId, topoRole,
                        protectionRole);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pw {\n");

    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tenantId: ").append(toIndentedString(tenantId)).append("\n");
    sb.append("    neId: ").append(toIndentedString(neId)).append("\n");
    sb.append("    peerAddress: ").append(toIndentedString(peerAddress)).append("\n");
    sb.append("    tunnelId: ").append(toIndentedString(tunnelId)).append("\n");
    sb.append("    topoRole: ").append(toIndentedString(topoRole)).append("\n");
    sb.append("    protectionRole: ").append(toIndentedString(protectionRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

