/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Route
 */
@ApiModel(description = "Route")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class Route {

  @SerializedName("type")
  private String type = null;

  @SerializedName("staticRoutes")
  private StaticRoutes staticRoutes = null;

  @SerializedName("bgpRoutes")
  private BgpRoutes bgpRoutes = null;

  @SerializedName("isisRoute")
  private IsisRoute isisRoute = null;

  @SerializedName("ospfRoutes")
  private OspfRoutes ospfRoutes = null;

  public Route type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Route protocol type (static, bgp, ospf, isis)
   *
   * @return type
   */
  @ApiModelProperty(example = "null", required = true,
                    value = "Route protocol type (static, bgp, ospf, isis)")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Route staticRoutes(StaticRoutes staticRoutes) {
    this.staticRoutes = staticRoutes;
    return this;
  }

  /**
   * Get staticRoutes
   *
   * @return staticRoutes
   */
  @ApiModelProperty(example = "null", value = "")
  public StaticRoutes getStaticRoutes() {
    return staticRoutes;
  }

  public void setStaticRoutes(StaticRoutes staticRoutes) {
    this.staticRoutes = staticRoutes;
  }

  public Route bgpRoutes(BgpRoutes bgpRoutes) {
    this.bgpRoutes = bgpRoutes;
    return this;
  }

  /**
   * Get bgpRoutes
   *
   * @return bgpRoutes
   */
  @ApiModelProperty(example = "null", value = "")
  public BgpRoutes getBgpRoutes() {
    return bgpRoutes;
  }

  public void setBgpRoutes(BgpRoutes bgpRoutes) {
    this.bgpRoutes = bgpRoutes;
  }

  public Route isisRoute(IsisRoute isisRoute) {
    this.isisRoute = isisRoute;
    return this;
  }

  /**
   * Get isisRoute
   *
   * @return isisRoute
   */
  @ApiModelProperty(example = "null", value = "")
  public IsisRoute getIsisRoute() {
    return isisRoute;
  }

  public void setIsisRoute(IsisRoute isisRoute) {
    this.isisRoute = isisRoute;
  }

  public Route ospfRoutes(OspfRoutes ospfRoutes) {
    this.ospfRoutes = ospfRoutes;
    return this;
  }

  /**
   * Get ospfRoutes
   *
   * @return ospfRoutes
   */
  @ApiModelProperty(example = "null", value = "")
  public OspfRoutes getOspfRoutes() {
    return ospfRoutes;
  }

  public void setOspfRoutes(OspfRoutes ospfRoutes) {
    this.ospfRoutes = ospfRoutes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Route route = (Route) o;
    return Objects.equals(this.type, route.type) &&
           Objects.equals(this.staticRoutes, route.staticRoutes) &&
           Objects.equals(this.bgpRoutes, route.bgpRoutes) &&
           Objects.equals(this.isisRoute, route.isisRoute) &&
           Objects.equals(this.ospfRoutes, route.ospfRoutes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, staticRoutes, bgpRoutes, isisRoute, ospfRoutes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Route {\n");

    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    staticRoutes: ").append(toIndentedString(staticRoutes)).append("\n");
    sb.append("    bgpRoutes: ").append(toIndentedString(bgpRoutes)).append("\n");
    sb.append("    isisRoute: ").append(toIndentedString(isisRoute)).append("\n");
    sb.append("    ospfRoutes: ").append(toIndentedString(ospfRoutes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

