/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Spoke Group
 */
@ApiModel(description = "Spoke Group")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class SpokeGroup {

  @SerializedName("localBridge")
  private Boolean localBridge = null;

  @SerializedName("spokeAc")
  private List<SpokeAcs> spokeAc = new ArrayList<SpokeAcs>();

  public SpokeGroup localBridge(Boolean localBridge) {
    this.localBridge = localBridge;
    return this;
  }

  /**
   * Is Local Bridge (true, false)
   *
   * @return localBridge
   */
  @ApiModelProperty(example = "null", value = "Is Local Bridge (true, false)")
  public Boolean getLocalBridge() {
    return localBridge;
  }

  public void setLocalBridge(Boolean localBridge) {
    this.localBridge = localBridge;
  }

  public SpokeGroup spokeAc(List<SpokeAcs> spokeAc) {
    this.spokeAc = spokeAc;
    return this;
  }

  /**
   * Get spokeAc
   *
   * @return spokeAc
   */
  @ApiModelProperty(example = "null", value = "")
  public List<SpokeAcs> getSpokeAc() {
    return spokeAc;
  }

  public void setSpokeAc(List<SpokeAcs> spokeAc) {
    this.spokeAc = spokeAc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpokeGroup spokeGroup = (SpokeGroup) o;
    return Objects.equals(this.localBridge, spokeGroup.localBridge) &&
           Objects.equals(this.spokeAc, spokeGroup.spokeAc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(localBridge, spokeAc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpokeGroup {\n");

    sb.append("    localBridge: ").append(toIndentedString(localBridge)).append("\n");
    sb.append("    spokeAc: ").append(toIndentedString(spokeAc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

