/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Topology Service. a SpokeGroup and a list of HubGroup
 */
@ApiModel(description = "Topology Service. a SpokeGroup and a list of HubGroup")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class TopologyService {

  @SerializedName("hubGroups")
  private List<HubGroup> hubGroups = new ArrayList<HubGroup>();

  @SerializedName("spokeGroup")
  private SpokeGroup spokeGroup = null;

  public TopologyService hubGroups(List<HubGroup> hubGroups) {
    this.hubGroups = hubGroups;
    return this;
  }

  /**
   * The list of Hub AC Group
   *
   * @return hubGroups
   */
  @ApiModelProperty(example = "null", required = true, value = "The list of Hub AC Group")
  public List<HubGroup> getHubGroups() {
    return hubGroups;
  }

  public void setHubGroups(List<HubGroup> hubGroups) {
    this.hubGroups = hubGroups;
  }

  public TopologyService spokeGroup(SpokeGroup spokeGroup) {
    this.spokeGroup = spokeGroup;
    return this;
  }

  /**
   * Get spokeGroup
   *
   * @return spokeGroup
   */
  @ApiModelProperty(example = "null", required = true, value = "")
  public SpokeGroup getSpokeGroup() {
    return spokeGroup;
  }

  public void setSpokeGroup(SpokeGroup spokeGroup) {
    this.spokeGroup = spokeGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TopologyService topologyService = (TopologyService) o;
    return Objects.equals(this.hubGroups, topologyService.hubGroups) &&
           Objects.equals(this.spokeGroup, topologyService.spokeGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hubGroups, spokeGroup);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TopologyService {\n");

    sb.append("    hubGroups: ").append(toIndentedString(hubGroups)).append("\n");
    sb.append("    spokeGroup: ").append(toIndentedString(spokeGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

