/**
 * L3VpnService Sbi Adapter Interface
 * Orchestrator SDN-O SBI Reference V1.0-L3VPN
 *
 * OpenAPI spec version: 0.1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package openo.sdno.driver.zte.sptn.models.north;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Vrrp configuration
 */
@ApiModel(description = "Vrrp configuration")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen",
                            date = "2016-08-12T11:26:39.981+08:00")
public class Vrrp {

  @SerializedName("virtualIp")
  private String virtualIp = null;

  @SerializedName("vrrpTrackBfd")
  private String vrrpTrackBfd = null;

  @SerializedName("bfdParamter")
  private BfdParameter bfdParamter = null;

  public Vrrp virtualIp(String virtualIp) {
    this.virtualIp = virtualIp;
    return this;
  }

  /**
   * Virtual IP
   *
   * @return virtualIp
   */
  @ApiModelProperty(example = "null", value = "Virtual IP")
  public String getVirtualIp() {
    return virtualIp;
  }

  public void setVirtualIp(String virtualIp) {
    this.virtualIp = virtualIp;
  }

  public Vrrp vrrpTrackBfd(String vrrpTrackBfd) {
    this.vrrpTrackBfd = vrrpTrackBfd;
    return this;
  }

  /**
   * Track Bidirectional Forwarding Detection (true, false)
   *
   * @return vrrpTrackBfd
   */
  @ApiModelProperty(example = "null",
                    value = "Track Bidirectional Forwarding Detection (true, false)")
  public String getVrrpTrackBfd() {
    return vrrpTrackBfd;
  }

  public void setVrrpTrackBfd(String vrrpTrackBfd) {
    this.vrrpTrackBfd = vrrpTrackBfd;
  }

  public Vrrp bfdParamter(BfdParameter bfdParamter) {
    this.bfdParamter = bfdParamter;
    return this;
  }

  /**
   * Get bfdParamter
   *
   * @return bfdParamter
   */
  @ApiModelProperty(example = "null", value = "")
  public BfdParameter getBfdParamter() {
    return bfdParamter;
  }

  public void setBfdParamter(BfdParameter bfdParamter) {
    this.bfdParamter = bfdParamter;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vrrp vrrp = (Vrrp) o;
    return Objects.equals(this.virtualIp, vrrp.virtualIp) &&
           Objects.equals(this.vrrpTrackBfd, vrrp.vrrpTrackBfd) &&
           Objects.equals(this.bfdParamter, vrrp.bfdParamter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(virtualIp, vrrpTrackBfd, bfdParamter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vrrp {\n");

    sb.append("    virtualIp: ").append(toIndentedString(virtualIp)).append("\n");
    sb.append("    vrrpTrackBfd: ").append(toIndentedString(vrrpTrackBfd)).append("\n");
    sb.append("    bfdParamter: ").append(toIndentedString(bfdParamter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first
   * line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

