swagger: '2.0'
info:
  version: '0.1.0'
  title: L2VpnService Sbi Adapter Interface
  description: Orchestrator SDN-O SBI Reference V1.0-L2VPN
host: sdno.openo.org
basePath: /rest
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /plugin_adapter_nsp/v1/controllers/{controllerid}/united-sbi-service-l2vpn-vpws:service/l2vpnVpwss:
    post:
      summary: Create L2Vpn Connection
      description: Creates a L2Vpn Connection instance, need to pass in controller id
      produces:
        - application/json
      parameters:
        - name: controllerid
          in: path
          description: controller uuid
          required: true
          type: string
        - name: l2vpnVpws
          in: body
          description: L2Vpn Connection
          required: true
          schema:
            $ref: '#/definitions/L2Vpn'
      responses:
        '200':
          description: Create L2Vpn connection 
          schema:
            $ref: '#/definitions/L2Vpn'
  /plugin_adapter_nsp/v1/controllers/{controllerid}/united-sbi-service-l2vpn-vpws:service/l2vpnVpwss/l2vpnVpws/{vpnid}:
    delete:
      summary: Delete a L2Vpn Connection
      description: Delete a L2Vpn Connection, need to pass in controller id and vpn id
      produces:
        - application/json
      parameters:
        - name: controllerid
          in: path
          description: controller uuid
          required: true
          type: string
        - name: vpnid
          in: path
          description: L2Vpn Connection uuid
          required: true
          type: string
      responses:
        '200':
          description: Delete a L2Vpn connection 
          schema:
            $ref: '#/definitions/L2Vpn'
    get:
      summary: Query a L2Vpn Connection
      description: Query a L2Vpn Connection, need to pass in controller id and vpn id
      produces:
        - application/json
      parameters:
        - name: controllerid
          in: path
          description: controller uuid
          required: true
          type: string
        - name: vpnid
          in: path
          description: L2Vpn Connection uuid
          required: true
          type: string
      responses:
        '200':
          description: Query a L2Vpn connection 
          schema:
            $ref: '#/definitions/L2Vpn'
    put:
      summary: Update a L2Vpn Connection
      description: Update a L2Vpn Connection, need to pass in controller id and vpn id
      produces:
        - application/json
      parameters:
        - name: controllerid
          in: path
          description: controller uuid
          required: true
          type: string
        - name: vpnid
          in: path
          description: L2Vpn Connection uuid
          required: true
          type: string
        - name: l2vpnVpws
          in: body
          description: L2Vpn Connection instance
          required: true
          schema:
            $ref: '#/definitions/L2Vpn'
      responses:
        '200':
          description: Update a L2Vpn connection 
          schema:
            $ref: '#/definitions/L2Vpn'
  /svc/sbiadp/config/{controllerid}/united-sbi-service-l2vpn-vpws:service/l2vpnVpwss/l2vpnVpws/{vpnid}/acs:
    post:
      summary: Add a L2Ac Configuration to L2Vpn
      description: Add a L2Ac Configuration to L2Vpn, need to pass in controller id and vpn id
      produces:
        - application/json
      parameters:
        - name: controllerid
          in: path
          description: controller uuid
          required: true
          type: string
        - name: vpnid
          in: path
          description: L2Vpn connection uuid
          required: true
          type: string
        - name: ac
          in: body
          description: L2Ac Object
          required: true
          schema:
            $ref: '#/definitions/L2Ac'
      responses:
        '200':
          description: Add a L2Ac Configuration to L2Vpn 
          schema:
            $ref: '#/definitions/L2Ac'
  /rest/svc/sbiadp/config/{controllerid}/united-sbi-service-l2vpn-vpws:service/l2vpnVpwss/l2vpnVpws/{vpnid}/acs/ac/{acid}:
      delete:
        summary: Delete a L2Ac Configuration
        description: Delete a L2Ac Configuration, need to pass in controller id, vpn id and acid
        produces:
          - application/json
        parameters:
          - name: controllerid
            in: path
            description: controller uuid
            required: true
            type: string
          - name: vpnid
            in: path
            description: L2Vpn Connection uuid
            required: true
            type: string
          - name: acid
            in: path
            description: L2Ac uuid
            required: true
            type: string
        responses:
          '200':
            description: Delete a L2Ac Configuration 
            schema:
              $ref: '#/definitions/L2Ac'
      put:
        summary: Update a L2Ac configuration
        description: Update a L2Ac configuration, need to pass in controller id, vpn id and acid
        produces:
          - application/json
        parameters:
          - name: controllerid
            in: path
            description: controller uuid
            required: true
            type: string
          - name: vpnid
            in: path
            description: L2Vpn Connection uuid
            required: true
            type: string
          - name: acid
            in: path
            description: L2Ac uuid
            required: true
            type: string
          - name: ac
            in: body
            description: L2Ac instance
            required: true
            schema:
              $ref: '#/definitions/L2Ac'
        responses:
          '200':
            description: Update a L2Ac configuration
            schema:
              $ref: '#/definitions/L2Ac'
definitions:
  L2Vpn:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        description: L2Vpn Connection UUID
        format: string
      name:
        type: string
        description: L2Vpn Connection name
      tenantId:
        type: string
        description: tenant UUID
      description:
        type: string
        description: description of L2Vpn Connction
      topology:
        type: string
        description: This identify the connection mode of vpns, including none, hub-spoke and full-mesh
      adminStatus:
        type: string
        description: L2VPN Connection  management status, including adminUp and adminDown
      operStatus:
        type: string
        description: The running status of connection in controller, the adapter need fill this parameter, including operateUp and operateDown
      tunnelService:
        $ref: '#/definitions/TunnelService'
      mtu:
        type: integer
        description: Mtu of L2Vpn business, range from 46 to 9600
        format: int16
      acs:
        $ref: '#/definitions/L2Acs'
      CtrlWordType: 
        type: string
        description: Control Word type, including disable and enable
      Pws:
        $ref: '#/definitions/Pws'
      SignalType:
        type: string
        description: Singaling Type of L2Vpn, including static,ldp,ldp and sr-te
      EncapsulationType:
        type: string
        description: Encapsulation Type of L2Vpn, including eth and vlan
  TunnelService:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        description: Type of tunnel policy, including auto-select、mpls-te、vxlan、gre
        format: string
      autoSelect:
        $ref: '#/definitions/AutoSelectPolicy'
      mplsTe:
        $ref: '#/definitions/MplsTePolicy'
      particularConstraints:
        $ref: '#/definitions/ParticularConstraints'
  AutoSelectPolicy:
    type: object
    required:
      - loadBalanceNumber
    properties:
      loadBalanceNumber:
        type: integer
        description: Auto Select tunnel Load Number range from 1 to 32
        format: int32
      autoSelectTunnels:
        $ref: '#/definitions/AutoSelectTunnels'
  AutoSelectTunnels:
    type: object
    required:
      - autoSelectTunnel
    properties: 
      autoSelectTunnel:
        items:
            $ref: '#/definitions/AutoSelectTunnel'
  AutoSelectTunnel:
    type: object
    required:
      - type
    properties: 
      type:
        type: string
        description: Tunnel type of Auto select tunnel policy
        format: string
      priority:
        type: integer
        description: Tunnel priority of Auto select tunnel policy
        format: int64
  ParticularConstraints:
    type: object
    required:
      - particularConstraint
    properties:
      particularConstraint:
        type: array
        description: List of particular constraints
        items:
          $ref: '#/definitions/ParticularConstraint'
  ParticularConstraint:
    type: object
    required:
      - ingressNe
    properties:
      ingressNe:
        type: string
        description: Ingress node of tunnel
        format: string
      egressNe:
        type: string
        description: Egress node of tunnel
        format: string
      type:
        type: string
        description: Type of tunnel constraint including binding and particular-mpls-te-tunnel
        format: string
      bindingTunnel:
        type: array
        description: List of binding tunnel
        items:
          type: string
      mplsTe:
        $ref: '#/definitions/MplsTePolicy'
  MplsTePolicy:
    type: object
    required:
      - signalType
    properties:
      signalType:
        type: string
        description: Tunnel type of Manual Select, including rsvp-te、sr-te、static-lsp
      manageProtocol:
        type: string
        description: Manage protocol, including netconf、pcep
      sharing:
        type: boolean
        description: Whether is shared, including true、false
      besteffort:
        type: boolean
        description: Whether is best effort, including true、false
      bandwidth:
        type: integer
        description: Tunnel bandwidth in kbps
      coRoute:
        type: boolean
        description: Whether to re Route, including true、false
      bfdEnable:
        type: boolean
        description: Whether to enable BFD Protocol, including true、false
      pathConstraint:
        $ref: '#/definitions/PathConstraint'
      pathProtectPolicy:
        $ref: '#/definitions/PathProtectPolicy'
  PathConstraint:
    type: object
    required:
      - setupPriority
    properties: 
      setupPriority:
        type: integer
        description: Setup priority of tunnel route constraints, range from 0 to 7
        format: int32
      holdupPriority:
        type: integer
        description: Holdup priority of tunnel route constraints, range from 0 to 7
        format: int32
      latency:
        type: integer
        description: Latency priority of tunnel route constraints, range from 0 to 60000000
        format: int32
  PathProtectPolicy:
    type: object
    required:
      - type
    properties: 
      type:
        type: string
        description: Type of tunnel protection policy 
      hotStandbyEnable:
        type: boolean
        description: Whether to enable hotstandby in tunnel protection, including true、false
      revertive:
        type: boolean
        description: Whether to revertive in tunnel protection including true、false
      bandwidthMode:
        type: string
        description: Bandwidth mode of tunnel protection including original-bandwidth、dynamic-bandwidth
      wtr:
        type: integer
        description: Wtr time of tunnel protection revertive  in us, range from 0 to 60000000
        format: int32
  L2Acs:
    type: object
    required: 
      - ac
    properties:
      ac:
        type: array
        description: Layer2 Vpn Access Point configuration
        items: 
          $ref: '#/definitions/L2Ac'
  L2Ac:
    type: object
    required:
      - externalQosPolicyId
    properties:
      externalQosPolicyId:
        type: string
        description: Id of External Qos Policy
      overrideFlows:
        $ref: '#/definitions/OverrideFlows'
  OverrideFlows:
    type: object
    required:
      - overrideFlow
    properties:
      overrideFlow:
        type: array
        description: Bandwidth  Configuration of Flow
        items:
          $ref: '#/definitions/OverrideFlow'
  OverrideFlow:
    type: object
    required:
      - externalFlowId
    properties:
      externalFlowId:
        type: string
        description: Flow ID in controller
      name:
        type: string
        description: Flow name in controller.
      direction:
        type: string
        description: Direction of flow, including ingress, egress 
      car:
        $ref: '#/definitions/QosIfCar'
  QosIfCar:
    type: object
    required:
      - enable
      - cir
      - pir
    properties:
      enable: 
        type: boolean
        description: Whether to enable car configuration, including true、false
      cir:
        type: integer
        description: Committed speed in kbps
        format: int32
      pir:
        type: integer
        description: Peak speed in kbps
        format: int32
      cbs:
        type: integer
        description: Committed burst Size in  bytes
        format: int32
      pbs:
        type: integer
        description: Peak burst Size in bytes
        format: int32
  Pws:
    type: object
    required: 
      - uuid
    properties:
      uuid:
        type: string
        description: uuid of private wire service
      pws:
        type: array
        description: private wire service
        items:
          $ref: '#/definitions/Pw'
  Pw:
    type: object
    required:
      - uuid 
    properties:
      uuid:
        type: string
        description: uuid of private wire
      name:
        type: string
        description: name of private wire
      description:
        type: string
        description: description of private wire
      tenantId:
        type: string
        description: tenant uuid
      neId:
        type: string
        description: real device uuid allocated by sdno
      peerAddress:
        type: string
        description:  remote ipaddress
      tunnelId:
        type: string
        description: tunnel id
      topoRole:
        type: string
        description: topology role, including hub, spoke
      protectionRole:
        type: string 
        description: protection role, including primary, backup